# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.order_options1 import OrderOptions1

class TestOrderOptions1(unittest.TestCase):
    """OrderOptions1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderOptions1:
        """Test OrderOptions1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderOptions1`
        """
        model = OrderOptions1()
        if include_optional:
            return OrderOptions1(
                order_options = openapi_client.models.order_options.OrderOptions(
                    order_options = openapi_client.models.order_options.OrderOptions(), )
            )
        else:
            return OrderOptions1(
        )
        """

    def testOrderOptions1(self):
        """Test OrderOptions1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
