# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.store_credit_refund_options1 import StoreCreditRefundOptions1

class TestStoreCreditRefundOptions1(unittest.TestCase):
    """StoreCreditRefundOptions1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StoreCreditRefundOptions1:
        """Test StoreCreditRefundOptions1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StoreCreditRefundOptions1`
        """
        model = StoreCreditRefundOptions1()
        if include_optional:
            return StoreCreditRefundOptions1(
                store_credit_refund_options = openapi_client.models.store_credit_refund_options.StoreCreditRefundOptions(
                    store_credit_refund_options = openapi_client.models.store_credit_refund_options.StoreCreditRefundOptions(), )
            )
        else:
            return StoreCreditRefundOptions1(
        )
        """

    def testStoreCreditRefundOptions1(self):
        """Test StoreCreditRefundOptions1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
