# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.gift_card_order4 import GiftCardOrder4

class TestGiftCardOrder4(unittest.TestCase):
    """GiftCardOrder4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GiftCardOrder4:
        """Test GiftCardOrder4
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GiftCardOrder4`
        """
        model = GiftCardOrder4()
        if include_optional:
            return GiftCardOrder4(
                id = '',
                revision = '',
                created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                source_channel_id = '',
                source_tenant_id = '0',
                source_order_id = '0',
                source_order_number = '',
                total_amount = '',
                currency = '',
                note = '',
                payment_status = 'UNKNOWN_PAYMENT_STATUS',
                fulfillment_status = 'UNKNOWN_FULFILLMENT_STATUS',
                status = 'UNKNOWN_ORDER_STATUS',
                buyer_info = openapi_client.models.buyer_info.BuyerInfo(
                    first_name = '', 
                    last_name = '', 
                    email = '', 
                    billing_address = '', 
                    source_customer_id = '0', 
                    billing_info = openapi_client.models.billing_info.BillingInfo(
                        address1 = '', 
                        address2 = '', 
                        city = '', 
                        company = '', 
                        country = '', 
                        state = '', 
                        zip = '', 
                        state_code = '', 
                        country_code = '', 
                        latitude = '', 
                        longitude = '', ), ),
                schedule_fulfill_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                rise_fulfilled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                source_fulfilled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                line_items = [
                    openapi_client.models.gift_card_line_item.GiftCardLineItem(
                        id = '', 
                        source_line_item_id = '0', 
                        source_variant_id = '0', 
                        gifting_info = openapi_client.models.gifting_info.GiftingInfo(
                            recipient_first_name = '', 
                            recipient_last_name = '', 
                            recipient_email = '', 
                            send_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            message = '', 
                            media_url = '', ), 
                        quantity = 56, 
                        fulfilled_quantity = 56, 
                        price = '', 
                        gift_card_initial_value = '', 
                        updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        fulfilled_data = openapi_client.models.fulfilled_data.FulfilledData(
                            gift_card_ids = [
                                ''
                                ], ), 
                        gift_card_expiration = openapi_client.models.expiration.Expiration(), 
                        side_effects = openapi_client.models.side_effects.SideEffects(
                            skip_notifications = True, ), 
                        gift_card_encrypted_code = '', )
                    ],
                fraud_message = '',
                fraud_type = 'UNKNOWN_FRAUD_TYPE',
                source_location_id = '0'
            )
        else:
            return GiftCardOrder4(
        )
        """

    def testGiftCardOrder4(self):
        """Test GiftCardOrder4"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
