# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.action_retry_request import ActionRetryRequest

class TestActionRetryRequest(unittest.TestCase):
    """ActionRetryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActionRetryRequest:
        """Test ActionRetryRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActionRetryRequest`
        """
        model = ActionRetryRequest()
        if include_optional:
            return ActionRetryRequest(
                activation_context = None,
                action_to_retry_data = None
            )
        else:
            return ActionRetryRequest(
        )
        """

    def testActionRetryRequest(self):
        """Test ActionRetryRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
