# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.query_transactions_internal_request import QueryTransactionsInternalRequest

class TestQueryTransactionsInternalRequest(unittest.TestCase):
    """QueryTransactionsInternalRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueryTransactionsInternalRequest:
        """Test QueryTransactionsInternalRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueryTransactionsInternalRequest`
        """
        model = QueryTransactionsInternalRequest()
        if include_optional:
            return QueryTransactionsInternalRequest(
                query = None
            )
        else:
            return QueryTransactionsInternalRequest(
        )
        """

    def testQueryTransactionsInternalRequest(self):
        """Test QueryTransactionsInternalRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
