# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_migration_gift_card_request import CreateMigrationGiftCardRequest

class TestCreateMigrationGiftCardRequest(unittest.TestCase):
    """CreateMigrationGiftCardRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateMigrationGiftCardRequest:
        """Test CreateMigrationGiftCardRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateMigrationGiftCardRequest`
        """
        model = CreateMigrationGiftCardRequest()
        if include_optional:
            return CreateMigrationGiftCardRequest(
                gift_card = None
            )
        else:
            return CreateMigrationGiftCardRequest(
        )
        """

    def testCreateMigrationGiftCardRequest(self):
        """Test CreateMigrationGiftCardRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
