# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.gift_card_order import GiftCardOrder

class TestGiftCardOrder(unittest.TestCase):
    """GiftCardOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GiftCardOrder:
        """Test GiftCardOrder
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GiftCardOrder`
        """
        model = GiftCardOrder()
        if include_optional:
            return GiftCardOrder(
                id = '',
                revision = '',
                created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                source_channel_id = '',
                source_tenant_id = '0',
                source_order_id = '0',
                source_order_number = '',
                total_amount = '',
                currency = '',
                note = '',
                payment_status = '',
                fulfillment_status = '',
                status = '',
                buyer_info = None,
                schedule_fulfill_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                rise_fulfilled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                source_fulfilled_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                line_items = [
                    None
                    ],
                fraud_message = '',
                fraud_type = '',
                source_location_id = '0'
            )
        else:
            return GiftCardOrder(
        )
        """

    def testGiftCardOrder(self):
        """Test GiftCardOrder"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
