# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.recipient_gift_card_recipient_service_v1_rise_recipients_query_post_query_recipients_request_body import RecipientGiftCardRecipientServiceV1RiseRecipientsQueryPostQueryRecipientsRequestBody

class TestRecipientGiftCardRecipientServiceV1RiseRecipientsQueryPostQueryRecipientsRequestBody(unittest.TestCase):
    """RecipientGiftCardRecipientServiceV1RiseRecipientsQueryPostQueryRecipientsRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecipientGiftCardRecipientServiceV1RiseRecipientsQueryPostQueryRecipientsRequestBody:
        """Test RecipientGiftCardRecipientServiceV1RiseRecipientsQueryPostQueryRecipientsRequestBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecipientGiftCardRecipientServiceV1RiseRecipientsQueryPostQueryRecipientsRequestBody`
        """
        model = RecipientGiftCardRecipientServiceV1RiseRecipientsQueryPostQueryRecipientsRequestBody()
        if include_optional:
            return RecipientGiftCardRecipientServiceV1RiseRecipientsQueryPostQueryRecipientsRequestBody(
                query = openapi_client.models.paging_method.pagingMethod(
                    cursor_paging = openapi_client.models.paging_method_cursor_paging.pagingMethod_cursorPaging(
                        limit = 0, 
                        cursor = '', ), )
            )
        else:
            return RecipientGiftCardRecipientServiceV1RiseRecipientsQueryPostQueryRecipientsRequestBody(
        )
        """

    def testRecipientGiftCardRecipientServiceV1RiseRecipientsQueryPostQueryRecipientsRequestBody(self):
        """Test RecipientGiftCardRecipientServiceV1RiseRecipientsQueryPostQueryRecipientsRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
