# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.refund_transaction_context import RefundTransactionContext

class TestRefundTransactionContext(unittest.TestCase):
    """RefundTransactionContext unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RefundTransactionContext:
        """Test RefundTransactionContext
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RefundTransactionContext`
        """
        model = RefundTransactionContext()
        if include_optional:
            return RefundTransactionContext(
                source_tenant_id = '0',
                source_channel_id = '',
                source_location_id = '0',
                source_order_id = '0',
                source_order_number = '0'
            )
        else:
            return RefundTransactionContext(
        )
        """

    def testRefundTransactionContext(self):
        """Test RefundTransactionContext"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
