# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.gift_card_line_item1 import GiftCardLineItem1

class TestGiftCardLineItem1(unittest.TestCase):
    """GiftCardLineItem1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GiftCardLineItem1:
        """Test GiftCardLineItem1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GiftCardLineItem1`
        """
        model = GiftCardLineItem1()
        if include_optional:
            return GiftCardLineItem1(
                id = '',
                source_line_item_id = '0',
                source_variant_id = '0',
                gifting_info = openapi_client.models.gifting_info.GiftingInfo(
                    recipient_first_name = '', 
                    recipient_last_name = '', 
                    recipient_email = '', 
                    send_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    message = '', 
                    media_url = '', ),
                quantity = 56,
                fulfilled_quantity = 56,
                price = '',
                gift_card_initial_value = '',
                updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                fulfilled_data = openapi_client.models.fulfilled_data.FulfilledData(
                    gift_card_ids = [
                        ''
                        ], ),
                gift_card_expiration = openapi_client.models.expiration.Expiration(),
                side_effects = openapi_client.models.side_effects.SideEffects(
                    skip_notifications = True, ),
                gift_card_encrypted_code = ''
            )
        else:
            return GiftCardLineItem1(
        )
        """

    def testGiftCardLineItem1(self):
        """Test GiftCardLineItem1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
