# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.wallet_action_creation_start_later_than_expiration_details import WalletActionCreationStartLaterThanExpirationDetails

class TestWalletActionCreationStartLaterThanExpirationDetails(unittest.TestCase):
    """WalletActionCreationStartLaterThanExpirationDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WalletActionCreationStartLaterThanExpirationDetails:
        """Test WalletActionCreationStartLaterThanExpirationDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WalletActionCreationStartLaterThanExpirationDetails`
        """
        model = WalletActionCreationStartLaterThanExpirationDetails()
        if include_optional:
            return WalletActionCreationStartLaterThanExpirationDetails(
                start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                expiration_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return WalletActionCreationStartLaterThanExpirationDetails(
        )
        """

    def testWalletActionCreationStartLaterThanExpirationDetails(self):
        """Test WalletActionCreationStartLaterThanExpirationDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
