# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.tags_modified import TagsModified

class TestTagsModified(unittest.TestCase):
    """TagsModified unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TagsModified:
        """Test TagsModified
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TagsModified`
        """
        model = TagsModified()
        if include_optional:
            return TagsModified(
                wallet_action = None,
                assigned_tags = None,
                unassigned_tags = None
            )
        else:
            return TagsModified(
        )
        """

    def testTagsModified(self):
        """Test TagsModified"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
