# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.refundable_amount import RefundableAmount

class TestRefundableAmount(unittest.TestCase):
    """RefundableAmount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RefundableAmount:
        """Test RefundableAmount
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RefundableAmount`
        """
        model = RefundableAmount()
        if include_optional:
            return RefundableAmount(
                wallet_action_id = '',
                amount = '',
                funding_transaction_id = ''
            )
        else:
            return RefundableAmount(
        )
        """

    def testRefundableAmount(self):
        """Test RefundableAmount"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
