# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_wallet_v2_request import CreateWalletV2Request

class TestCreateWalletV2Request(unittest.TestCase):
    """CreateWalletV2Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateWalletV2Request:
        """Test CreateWalletV2Request
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateWalletV2Request`
        """
        model = CreateWalletV2Request()
        if include_optional:
            return CreateWalletV2Request(
                currency = '',
                contact_details = None,
                customer_reference = None
            )
        else:
            return CreateWalletV2Request(
        )
        """

    def testCreateWalletV2Request(self):
        """Test CreateWalletV2Request"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
