# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.action_initiator2 import ActionInitiator2

class TestActionInitiator2(unittest.TestCase):
    """ActionInitiator2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActionInitiator2:
        """Test ActionInitiator2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActionInitiator2`
        """
        model = ActionInitiator2()
        if include_optional:
            return ActionInitiator2(
                type = '{\"order\":1,\"value\":\"APP\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}',
                id = ''
            )
        else:
            return ActionInitiator2(
        )
        """

    def testActionInitiator2(self):
        """Test ActionInitiator2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
