# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.expirationdateinthepast import EXPIRATIONDATEINTHEPAST

class TestEXPIRATIONDATEINTHEPAST(unittest.TestCase):
    """EXPIRATIONDATEINTHEPAST unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EXPIRATIONDATEINTHEPAST:
        """Test EXPIRATIONDATEINTHEPAST
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EXPIRATIONDATEINTHEPAST`
        """
        model = EXPIRATIONDATEINTHEPAST()
        if include_optional:
            return EXPIRATIONDATEINTHEPAST(
                message = '',
                details = openapi_client.models.expiration_date_in_the_past_details.EXPIRATION_DATE_IN_THE_PAST_details(
                    application_error = openapi_client.models.expiration_date_in_the_past_details_application_error.EXPIRATION_DATE_IN_THE_PAST_details_applicationError(
                        code = 'EXPIRATION_DATE_IN_THE_PAST', 
                        description = '', 
                        data = openapi_client.models.data.data(), ), )
            )
        else:
            return EXPIRATIONDATEINTHEPAST(
                message = '',
                details = openapi_client.models.expiration_date_in_the_past_details.EXPIRATION_DATE_IN_THE_PAST_details(
                    application_error = openapi_client.models.expiration_date_in_the_past_details_application_error.EXPIRATION_DATE_IN_THE_PAST_details_applicationError(
                        code = 'EXPIRATION_DATE_IN_THE_PAST', 
                        description = '', 
                        data = openapi_client.models.data.data(), ), ),
        )
        """

    def testEXPIRATIONDATEINTHEPAST(self):
        """Test EXPIRATIONDATEINTHEPAST"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
