# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.startlaterthanexpiration_details_application_error import STARTLATERTHANEXPIRATIONDetailsApplicationError

class TestSTARTLATERTHANEXPIRATIONDetailsApplicationError(unittest.TestCase):
    """STARTLATERTHANEXPIRATIONDetailsApplicationError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> STARTLATERTHANEXPIRATIONDetailsApplicationError:
        """Test STARTLATERTHANEXPIRATIONDetailsApplicationError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `STARTLATERTHANEXPIRATIONDetailsApplicationError`
        """
        model = STARTLATERTHANEXPIRATIONDetailsApplicationError()
        if include_optional:
            return STARTLATERTHANEXPIRATIONDetailsApplicationError(
                code = 'START_LATER_THAN_EXPIRATION',
                description = '',
                data = None
            )
        else:
            return STARTLATERTHANEXPIRATIONDetailsApplicationError(
                code = 'START_LATER_THAN_EXPIRATION',
                description = '',
        )
        """

    def testSTARTLATERTHANEXPIRATIONDetailsApplicationError(self):
        """Test STARTLATERTHANEXPIRATIONDetailsApplicationError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
