# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.transaction_details1 import TransactionDetails1

class TestTransactionDetails1(unittest.TestCase):
    """TransactionDetails1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionDetails1:
        """Test TransactionDetails1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionDetails1`
        """
        model = TransactionDetails1()
        if include_optional:
            return TransactionDetails1(
                last_transaction = openapi_client.models.transaction_wrapper.TransactionWrapper(
                    id = '', 
                    created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                last_decreasing_transaction = openapi_client.models.transaction_wrapper.TransactionWrapper(
                    id = '', 
                    created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                last_increasing_transaction = openapi_client.models.transaction_wrapper.TransactionWrapper(
                    id = '', 
                    created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return TransactionDetails1(
        )
        """

    def testTransactionDetails1(self):
        """Test TransactionDetails1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
