# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.wallet_action_end_options import WalletActionEndOptions

class TestWalletActionEndOptions(unittest.TestCase):
    """WalletActionEndOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WalletActionEndOptions:
        """Test WalletActionEndOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WalletActionEndOptions`
        """
        model = WalletActionEndOptions()
        if include_optional:
            return WalletActionEndOptions(
                wallet_action_end_options = openapi_client.models.wallet_action_end_options_wallet_action_end_options.WalletActionEndOptions_walletActionEndOptions(
                    wallet_action_id = '', 
                    transaction_id = '', 
                    liability = True, 
                    reason = 'CANCEL', )
            )
        else:
            return WalletActionEndOptions(
        )
        """

    def testWalletActionEndOptions(self):
        """Test WalletActionEndOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
