# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.paging_paging import PagingPaging

class TestPagingPaging(unittest.TestCase):
    """PagingPaging unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PagingPaging:
        """Test PagingPaging
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PagingPaging`
        """
        model = PagingPaging()
        if include_optional:
            return PagingPaging(
                limit = 0,
                offset = 0
            )
        else:
            return PagingPaging(
        )
        """

    def testPagingPaging(self):
        """Test PagingPaging"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
