# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.wallet_wallet_service_v1_rise_wallets_query_by_contact_post_query_wallets_by_contact_request_body import WalletWalletServiceV1RiseWalletsQueryByContactPostQueryWalletsByContactRequestBody

class TestWalletWalletServiceV1RiseWalletsQueryByContactPostQueryWalletsByContactRequestBody(unittest.TestCase):
    """WalletWalletServiceV1RiseWalletsQueryByContactPostQueryWalletsByContactRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WalletWalletServiceV1RiseWalletsQueryByContactPostQueryWalletsByContactRequestBody:
        """Test WalletWalletServiceV1RiseWalletsQueryByContactPostQueryWalletsByContactRequestBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WalletWalletServiceV1RiseWalletsQueryByContactPostQueryWalletsByContactRequestBody`
        """
        model = WalletWalletServiceV1RiseWalletsQueryByContactPostQueryWalletsByContactRequestBody()
        if include_optional:
            return WalletWalletServiceV1RiseWalletsQueryByContactPostQueryWalletsByContactRequestBody(
                query = openapi_client.models.query_by_contact.QueryByContact(
                    filter = openapi_client.models.filter.filter(
                        fields = openapi_client.models.fields.fields(
                            key = '', 
                            value = openapi_client.models.value.Value(), ), ), 
                    sort = [
                        openapi_client.models.sorting.Sorting(
                            field_name = '', 
                            order = 'ASC', )
                        ], 
                    limit = 0, )
            )
        else:
            return WalletWalletServiceV1RiseWalletsQueryByContactPostQueryWalletsByContactRequestBody(
                query = openapi_client.models.query_by_contact.QueryByContact(
                    filter = openapi_client.models.filter.filter(
                        fields = openapi_client.models.fields.fields(
                            key = '', 
                            value = openapi_client.models.value.Value(), ), ), 
                    sort = [
                        openapi_client.models.sorting.Sorting(
                            field_name = '', 
                            order = 'ASC', )
                        ], 
                    limit = 0, ),
        )
        """

    def testWalletWalletServiceV1RiseWalletsQueryByContactPostQueryWalletsByContactRequestBody(self):
        """Test WalletWalletServiceV1RiseWalletsQueryByContactPostQueryWalletsByContactRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
