# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.cursor_paging_metadata1 import CursorPagingMetadata1

class TestCursorPagingMetadata1(unittest.TestCase):
    """CursorPagingMetadata1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CursorPagingMetadata1:
        """Test CursorPagingMetadata1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CursorPagingMetadata1`
        """
        model = CursorPagingMetadata1()
        if include_optional:
            return CursorPagingMetadata1(
                count = 56,
                cursors = openapi_client.models.cursors.Cursors(
                    next = '', 
                    prev = '', ),
                has_next = True
            )
        else:
            return CursorPagingMetadata1(
        )
        """

    def testCursorPagingMetadata1(self):
        """Test CursorPagingMetadata1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
