# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.existingidempotencykey_details import EXISTINGIDEMPOTENCYKEYDetails

class TestEXISTINGIDEMPOTENCYKEYDetails(unittest.TestCase):
    """EXISTINGIDEMPOTENCYKEYDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EXISTINGIDEMPOTENCYKEYDetails:
        """Test EXISTINGIDEMPOTENCYKEYDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EXISTINGIDEMPOTENCYKEYDetails`
        """
        model = EXISTINGIDEMPOTENCYKEYDetails()
        if include_optional:
            return EXISTINGIDEMPOTENCYKEYDetails(
                application_error = openapi_client.models.existing_idempotency_key_details_application_error.EXISTING_IDEMPOTENCY_KEY_details_applicationError(
                    code = 'EXISTING_IDEMPOTENCY_KEY', 
                    description = '', 
                    data = openapi_client.models.data.data(), )
            )
        else:
            return EXISTINGIDEMPOTENCYKEYDetails(
                application_error = openapi_client.models.existing_idempotency_key_details_application_error.EXISTING_IDEMPOTENCY_KEY_details_applicationError(
                    code = 'EXISTING_IDEMPOTENCY_KEY', 
                    description = '', 
                    data = openapi_client.models.data.data(), ),
        )
        """

    def testEXISTINGIDEMPOTENCYKEYDetails(self):
        """Test EXISTINGIDEMPOTENCYKEYDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
