# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.if_filter import IfFilter

class TestIfFilter(unittest.TestCase):
    """IfFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IfFilter:
        """Test IfFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IfFilter`
        """
        model = IfFilter()
        if include_optional:
            return IfFilter(
                condition = '',
                true_post_actions = [
                    None
                    ],
                false_post_actions = [
                    None
                    ],
                true_post_actions_ids = [
                    ''
                    ],
                false_post_actions_ids = [
                    ''
                    ]
            )
        else:
            return IfFilter(
        )
        """

    def testIfFilter(self):
        """Test IfFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
