# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.date_histogram_results1 import DateHistogramResults1

class TestDateHistogramResults1(unittest.TestCase):
    """DateHistogramResults1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DateHistogramResults1:
        """Test DateHistogramResults1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DateHistogramResults1`
        """
        model = DateHistogramResults1()
        if include_optional:
            return DateHistogramResults1(
                date_histogram = openapi_client.models.date_histogram_results.DateHistogramResults(
                    date_histogram = openapi_client.models.date_histogram_results.DateHistogramResults(), )
            )
        else:
            return DateHistogramResults1(
        )
        """

    def testDateHistogramResults1(self):
        """Test DateHistogramResults1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
