# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_method_refund_options import PaymentMethodRefundOptions

class TestPaymentMethodRefundOptions(unittest.TestCase):
    """PaymentMethodRefundOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentMethodRefundOptions:
        """Test PaymentMethodRefundOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentMethodRefundOptions`
        """
        model = PaymentMethodRefundOptions()
        if include_optional:
            return PaymentMethodRefundOptions(
                payment_method_refund_options = openapi_client.models.payment_method_refund_options_payment_method_refund_options.PaymentMethodRefundOptions_paymentMethodRefundOptions(
                    order_id = '', 
                    liability = True, 
                    order_number = '', 
                    active_funding_transaction = openapi_client.models.payment_method_refund_wallet_action_details.PaymentMethodRefundWalletActionDetails(
                        wallet_action_id = '', 
                        funding_transaction_id = '', ), )
            )
        else:
            return PaymentMethodRefundOptions(
        )
        """

    def testPaymentMethodRefundOptions(self):
        """Test PaymentMethodRefundOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
