# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.rate_limiting import RateLimiting

class TestRateLimiting(unittest.TestCase):
    """RateLimiting unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RateLimiting:
        """Test RateLimiting
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RateLimiting`
        """
        model = RateLimiting()
        if include_optional:
            return RateLimiting(
                max_num_of_activations = 1.337,
                max_num_of_activations_expression = '',
                time_frame_in_minutes = 56,
                time_frame_in_minutes_expression = '',
                key_jsonata = '',
                post_actions = [
                    None
                    ],
                post_actions_ids = [
                    ''
                    ]
            )
        else:
            return RateLimiting(
        )
        """

    def testRateLimiting(self):
        """Test RateLimiting"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
