# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.wallet_wallet_service_v1_rise_wallets_issue_post_get_or_create_wallet_request_body import WalletWalletServiceV1RiseWalletsIssuePostGetOrCreateWalletRequestBody

class TestWalletWalletServiceV1RiseWalletsIssuePostGetOrCreateWalletRequestBody(unittest.TestCase):
    """WalletWalletServiceV1RiseWalletsIssuePostGetOrCreateWalletRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WalletWalletServiceV1RiseWalletsIssuePostGetOrCreateWalletRequestBody:
        """Test WalletWalletServiceV1RiseWalletsIssuePostGetOrCreateWalletRequestBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WalletWalletServiceV1RiseWalletsIssuePostGetOrCreateWalletRequestBody`
        """
        model = WalletWalletServiceV1RiseWalletsIssuePostGetOrCreateWalletRequestBody()
        if include_optional:
            return WalletWalletServiceV1RiseWalletsIssuePostGetOrCreateWalletRequestBody(
                customer_reference = openapi_client.models.customer_reference.CustomerReference(
                    source_channel_id = '', 
                    source_tenant_id = '0', 
                    source_customer_id = '0', 
                    first_name = '', 
                    last_name = '', 
                    phone = '', 
                    email = '', ),
                currency = ''
            )
        else:
            return WalletWalletServiceV1RiseWalletsIssuePostGetOrCreateWalletRequestBody(
                customer_reference = openapi_client.models.customer_reference.CustomerReference(
                    source_channel_id = '', 
                    source_tenant_id = '0', 
                    source_customer_id = '0', 
                    first_name = '', 
                    last_name = '', 
                    phone = '', 
                    email = '', ),
        )
        """

    def testWalletWalletServiceV1RiseWalletsIssuePostGetOrCreateWalletRequestBody(self):
        """Test WalletWalletServiceV1RiseWalletsIssuePostGetOrCreateWalletRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
