# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.gift_card_line_item import GiftCardLineItem

class TestGiftCardLineItem(unittest.TestCase):
    """GiftCardLineItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GiftCardLineItem:
        """Test GiftCardLineItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GiftCardLineItem`
        """
        model = GiftCardLineItem()
        if include_optional:
            return GiftCardLineItem(
                id = '',
                source_line_item_id = '0',
                source_variant_id = '0',
                gifting_info = None,
                quantity = 56,
                fulfilled_quantity = 56,
                price = '',
                gift_card_initial_value = '',
                updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                fulfilled_data = None,
                gift_card_expiration = None,
                side_effects = None,
                gift_card_encrypted_code = ''
            )
        else:
            return GiftCardLineItem(
        )
        """

    def testGiftCardLineItem(self):
        """Test GiftCardLineItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
