# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.workflow_options import WorkflowOptions

class TestWorkflowOptions(unittest.TestCase):
    """WorkflowOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkflowOptions:
        """Test WorkflowOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkflowOptions`
        """
        model = WorkflowOptions()
        if include_optional:
            return WorkflowOptions(
                workflow_options = openapi_client.models.workflow_options_workflow_options.WorkflowOptions_workflowOptions(
                    workflow_id = '', )
            )
        else:
            return WorkflowOptions(
        )
        """

    def testWorkflowOptions(self):
        """Test WorkflowOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
