# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.giftcardexpired_details import GIFTCARDEXPIREDDetails

class TestGIFTCARDEXPIREDDetails(unittest.TestCase):
    """GIFTCARDEXPIREDDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GIFTCARDEXPIREDDetails:
        """Test GIFTCARDEXPIREDDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GIFTCARDEXPIREDDetails`
        """
        model = GIFTCARDEXPIREDDetails()
        if include_optional:
            return GIFTCARDEXPIREDDetails(
                application_error = openapi_client.models.gift_card_expired_details_application_error.GIFT_CARD_EXPIRED_details_applicationError(
                    code = 'GIFT_CARD_EXPIRED', 
                    description = '', 
                    data = openapi_client.models.data.data(), )
            )
        else:
            return GIFTCARDEXPIREDDetails(
                application_error = openapi_client.models.gift_card_expired_details_application_error.GIFT_CARD_EXPIRED_details_applicationError(
                    code = 'GIFT_CARD_EXPIRED', 
                    description = '', 
                    data = openapi_client.models.data.data(), ),
        )
        """

    def testGIFTCARDEXPIREDDetails(self):
        """Test GIFTCARDEXPIREDDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
