# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.o_auth_oauth2_token_post_some_operation_request_body import OAuthOauth2TokenPostSomeOperationRequestBody

class TestOAuthOauth2TokenPostSomeOperationRequestBody(unittest.TestCase):
    """OAuthOauth2TokenPostSomeOperationRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OAuthOauth2TokenPostSomeOperationRequestBody:
        """Test OAuthOauth2TokenPostSomeOperationRequestBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OAuthOauth2TokenPostSomeOperationRequestBody`
        """
        model = OAuthOauth2TokenPostSomeOperationRequestBody()
        if include_optional:
            return OAuthOauth2TokenPostSomeOperationRequestBody(
                grant_type = '',
                client_id = '',
                client_secret = '',
                instance_id = ''
            )
        else:
            return OAuthOauth2TokenPostSomeOperationRequestBody(
        )
        """

    def testOAuthOauth2TokenPostSomeOperationRequestBody(self):
        """Test OAuthOauth2TokenPostSomeOperationRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
