# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.idempotency1 import Idempotency1

class TestIdempotency1(unittest.TestCase):
    """Idempotency1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Idempotency1:
        """Test Idempotency1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Idempotency1`
        """
        model = Idempotency1()
        if include_optional:
            return Idempotency1(
                key = '0',
                ttl_in_milliseconds = ''
            )
        else:
            return Idempotency1(
        )
        """

    def testIdempotency1(self):
        """Test Idempotency1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
