# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.transaction_transaction_query_service_v1_rise_gift_cards_transactions_query_post_query_transactions_request_body import TransactionTransactionQueryServiceV1RiseGiftCardsTransactionsQueryPostQueryTransactionsRequestBody

class TestTransactionTransactionQueryServiceV1RiseGiftCardsTransactionsQueryPostQueryTransactionsRequestBody(unittest.TestCase):
    """TransactionTransactionQueryServiceV1RiseGiftCardsTransactionsQueryPostQueryTransactionsRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionTransactionQueryServiceV1RiseGiftCardsTransactionsQueryPostQueryTransactionsRequestBody:
        """Test TransactionTransactionQueryServiceV1RiseGiftCardsTransactionsQueryPostQueryTransactionsRequestBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionTransactionQueryServiceV1RiseGiftCardsTransactionsQueryPostQueryTransactionsRequestBody`
        """
        model = TransactionTransactionQueryServiceV1RiseGiftCardsTransactionsQueryPostQueryTransactionsRequestBody()
        if include_optional:
            return TransactionTransactionQueryServiceV1RiseGiftCardsTransactionsQueryPostQueryTransactionsRequestBody(
                query = openapi_client.models.query_v2.QueryV2(
                    filter = openapi_client.models.filter.filter(
                        fields = openapi_client.models.fields.fields(
                            key = '', 
                            value = openapi_client.models.value.Value(), ), ), 
                    sort = [
                        openapi_client.models.sorting.Sorting(
                            field_name = '', 
                            order = 'ASC', )
                        ], 
                    fields = [
                        ''
                        ], 
                    fieldsets = [
                        ''
                        ], )
            )
        else:
            return TransactionTransactionQueryServiceV1RiseGiftCardsTransactionsQueryPostQueryTransactionsRequestBody(
                query = openapi_client.models.query_v2.QueryV2(
                    filter = openapi_client.models.filter.filter(
                        fields = openapi_client.models.fields.fields(
                            key = '', 
                            value = openapi_client.models.value.Value(), ), ), 
                    sort = [
                        openapi_client.models.sorting.Sorting(
                            field_name = '', 
                            order = 'ASC', )
                        ], 
                    fields = [
                        ''
                        ], 
                    fieldsets = [
                        ''
                        ], ),
        )
        """

    def testTransactionTransactionQueryServiceV1RiseGiftCardsTransactionsQueryPostQueryTransactionsRequestBody(self):
        """Test TransactionTransactionQueryServiceV1RiseGiftCardsTransactionsQueryPostQueryTransactionsRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
