# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.date_histogram_result1 import DateHistogramResult1

class TestDateHistogramResult1(unittest.TestCase):
    """DateHistogramResult1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DateHistogramResult1:
        """Test DateHistogramResult1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DateHistogramResult1`
        """
        model = DateHistogramResult1()
        if include_optional:
            return DateHistogramResult1(
                value = '',
                count = 56
            )
        else:
            return DateHistogramResult1(
        )
        """

    def testDateHistogramResult1(self):
        """Test DateHistogramResult1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
