# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.side_effects2 import SideEffects2

class TestSideEffects2(unittest.TestCase):
    """SideEffects2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SideEffects2:
        """Test SideEffects2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SideEffects2`
        """
        model = SideEffects2()
        if include_optional:
            return SideEffects2(
                skip_notifications = True
            )
        else:
            return SideEffects2(
        )
        """

    def testSideEffects2(self):
        """Test SideEffects2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
