# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.nested_aggregation_results1_one_of5_nested import NestedAggregationResults1OneOf5Nested

class TestNestedAggregationResults1OneOf5Nested(unittest.TestCase):
    """NestedAggregationResults1OneOf5Nested unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NestedAggregationResults1OneOf5Nested:
        """Test NestedAggregationResults1OneOf5Nested
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NestedAggregationResults1OneOf5Nested`
        """
        model = NestedAggregationResults1OneOf5Nested()
        if include_optional:
            return NestedAggregationResults1OneOf5Nested(
                results = [
                    openapi_client.models.results.Results()
                    ]
            )
        else:
            return NestedAggregationResults1OneOf5Nested(
        )
        """

    def testNestedAggregationResults1OneOf5Nested(self):
        """Test NestedAggregationResults1OneOf5Nested"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
