# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.nested_aggregation_results1 import NestedAggregationResults1

class TestNestedAggregationResults1(unittest.TestCase):
    """NestedAggregationResults1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NestedAggregationResults1:
        """Test NestedAggregationResults1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NestedAggregationResults1`
        """
        model = NestedAggregationResults1()
        if include_optional:
            return NestedAggregationResults1(
                name = '',
                type = '{\"order\":1,\"value\":\"VALUE\",\"description\":\"Calculates the distribution of a specific field\'s values within a dataset, providing insights into the overall distribution and key statistics of those values.\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}',
                field_path = '',
                values = openapi_client.models.value_results.ValueResults(
                    values = openapi_client.models.value_results.ValueResults(), ),
                ranges = openapi_client.models.range_results.RangeResults(
                    ranges = openapi_client.models.range_results.RangeResults(), ),
                scalar = openapi_client.models.scalar_result.ScalarResult(
                    scalar = openapi_client.models.scalar_result.ScalarResult(), ),
                grouped_by_value = openapi_client.models.grouped_by_value.groupedByValue(),
                date_histogram = openapi_client.models.date_histogram_results.DateHistogramResults(
                    date_histogram = openapi_client.models.date_histogram_results.DateHistogramResults(), ),
                nested = openapi_client.models.nested_results.NestedResults(
                    nested = openapi_client.models.nested_results.NestedResults(), )
            )
        else:
            return NestedAggregationResults1(
        )
        """

    def testNestedAggregationResults1(self):
        """Test NestedAggregationResults1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
