# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.decrease_balance_response import DecreaseBalanceResponse

class TestDecreaseBalanceResponse(unittest.TestCase):
    """DecreaseBalanceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DecreaseBalanceResponse:
        """Test DecreaseBalanceResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DecreaseBalanceResponse`
        """
        model = DecreaseBalanceResponse()
        if include_optional:
            return DecreaseBalanceResponse(
                transaction = openapi_client.models.transaction.Transaction(
                    id = '', 
                    created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    type = 'REDEEM', 
                    gift_card_id = '', 
                    amount = '', 
                    operation_type = 'ADD', 
                    idempotency_key = '0', 
                    updated_balance = '', 
                    source_info = openapi_client.models.transaction_source_info.TransactionSourceInfo(
                        initiator = openapi_client.models.action_initiator.ActionInitiator(
                            type = 'APP', 
                            id = '', ), 
                        source_tenant_id = '0', 
                        source_channel_id = '', 
                        source_location_id = '0', ), 
                    external_event = openapi_client.models.external_event.ExternalEvent(
                        name = 'ORDER', 
                        description = '0', ), 
                    external_id = '', ),
                balance = '',
                currency = ''
            )
        else:
            return DecreaseBalanceResponse(
        )
        """

    def testDecreaseBalanceResponse(self):
        """Test DecreaseBalanceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
