# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.nested_aggregation_results1_one_of3 import NestedAggregationResults1OneOf3

class TestNestedAggregationResults1OneOf3(unittest.TestCase):
    """NestedAggregationResults1OneOf3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NestedAggregationResults1OneOf3:
        """Test NestedAggregationResults1OneOf3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NestedAggregationResults1OneOf3`
        """
        model = NestedAggregationResults1OneOf3()
        if include_optional:
            return NestedAggregationResults1OneOf3(
                grouped_by_value = None
            )
        else:
            return NestedAggregationResults1OneOf3(
        )
        """

    def testNestedAggregationResults1OneOf3(self):
        """Test NestedAggregationResults1OneOf3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
