# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.query_wallet_action_response import QueryWalletActionResponse

class TestQueryWalletActionResponse(unittest.TestCase):
    """QueryWalletActionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueryWalletActionResponse:
        """Test QueryWalletActionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueryWalletActionResponse`
        """
        model = QueryWalletActionResponse()
        if include_optional:
            return QueryWalletActionResponse(
                wallet_actions = [
                    None
                    ],
                paging_metadata = None
            )
        else:
            return QueryWalletActionResponse(
        )
        """

    def testQueryWalletActionResponse(self):
        """Test QueryWalletActionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
