# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.wallet_action_wallet_action_service_v1_rise_wallet_actions_by_customer_reference_post_create_wallet_action_by_customer_reference_request_body import WalletActionWalletActionServiceV1RiseWalletActionsByCustomerReferencePostCreateWalletActionByCustomerReferenceRequestBody

class TestWalletActionWalletActionServiceV1RiseWalletActionsByCustomerReferencePostCreateWalletActionByCustomerReferenceRequestBody(unittest.TestCase):
    """WalletActionWalletActionServiceV1RiseWalletActionsByCustomerReferencePostCreateWalletActionByCustomerReferenceRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WalletActionWalletActionServiceV1RiseWalletActionsByCustomerReferencePostCreateWalletActionByCustomerReferenceRequestBody:
        """Test WalletActionWalletActionServiceV1RiseWalletActionsByCustomerReferencePostCreateWalletActionByCustomerReferenceRequestBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WalletActionWalletActionServiceV1RiseWalletActionsByCustomerReferencePostCreateWalletActionByCustomerReferenceRequestBody`
        """
        model = WalletActionWalletActionServiceV1RiseWalletActionsByCustomerReferencePostCreateWalletActionByCustomerReferenceRequestBody()
        if include_optional:
            return WalletActionWalletActionServiceV1RiseWalletActionsByCustomerReferencePostCreateWalletActionByCustomerReferenceRequestBody(
                customer_reference = openapi_client.models.customer_reference.CustomerReference(
                    source_channel_id = '', 
                    source_tenant_id = '0', 
                    source_customer_id = '0', 
                    first_name = '', 
                    last_name = '', 
                    phone = '', 
                    email = '', ),
                wallet_action = openapi_client.models.wallet_action.WalletAction(
                    id = '', 
                    revision = '', 
                    created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    expiration_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    disable_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    amount = '', 
                    note = '', 
                    type = 'UNKNOWN', 
                    wallet_action_started = openapi_client.models.wallet_action_execution_details.WalletActionExecutionDetails(
                        transaction_id = '', 
                        execution_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                    wallet_action_ended = openapi_client.models.wallet_action_execution_details.WalletActionExecutionDetails(
                        transaction_id = '', 
                        execution_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                    status = 'PENDING', 
                    source = openapi_client.models.action_initiator.ActionInitiator(
                        type = 'APP', 
                        id = '', ), 
                    notifications = openapi_client.models.notifications.Notifications(
                        email_params = openapi_client.models.email_params.EmailParams(
                            skip_email_dispatch = True, 
                            override_template_id = '', ), ), 
                    liability = True, 
                    store_credit_context = openapi_client.models.store_credit_context.StoreCreditContext(
                        issuer = 'WORKFLOW', 
                        issuer_id = '0', 
                        note = '0', 
                        source_channel_id = '', 
                        source_tenant_id = '0', ), 
                    external_event = openapi_client.models.external_event.ExternalEvent(
                        name = 'ORDER', 
                        description = '0', ), 
                    wallet_id = '', 
                    idempotency_key = '0', ),
                new_wallet_currency = ''
            )
        else:
            return WalletActionWalletActionServiceV1RiseWalletActionsByCustomerReferencePostCreateWalletActionByCustomerReferenceRequestBody(
                customer_reference = openapi_client.models.customer_reference.CustomerReference(
                    source_channel_id = '', 
                    source_tenant_id = '0', 
                    source_customer_id = '0', 
                    first_name = '', 
                    last_name = '', 
                    phone = '', 
                    email = '', ),
                wallet_action = openapi_client.models.wallet_action.WalletAction(
                    id = '', 
                    revision = '', 
                    created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    expiration_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    disable_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    amount = '', 
                    note = '', 
                    type = 'UNKNOWN', 
                    wallet_action_started = openapi_client.models.wallet_action_execution_details.WalletActionExecutionDetails(
                        transaction_id = '', 
                        execution_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                    wallet_action_ended = openapi_client.models.wallet_action_execution_details.WalletActionExecutionDetails(
                        transaction_id = '', 
                        execution_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                    status = 'PENDING', 
                    source = openapi_client.models.action_initiator.ActionInitiator(
                        type = 'APP', 
                        id = '', ), 
                    notifications = openapi_client.models.notifications.Notifications(
                        email_params = openapi_client.models.email_params.EmailParams(
                            skip_email_dispatch = True, 
                            override_template_id = '', ), ), 
                    liability = True, 
                    store_credit_context = openapi_client.models.store_credit_context.StoreCreditContext(
                        issuer = 'WORKFLOW', 
                        issuer_id = '0', 
                        note = '0', 
                        source_channel_id = '', 
                        source_tenant_id = '0', ), 
                    external_event = openapi_client.models.external_event.ExternalEvent(
                        name = 'ORDER', 
                        description = '0', ), 
                    wallet_id = '', 
                    idempotency_key = '0', ),
        )
        """

    def testWalletActionWalletActionServiceV1RiseWalletActionsByCustomerReferencePostCreateWalletActionByCustomerReferenceRequestBody(self):
        """Test WalletActionWalletActionServiceV1RiseWalletActionsByCustomerReferencePostCreateWalletActionByCustomerReferenceRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
