# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.set_variables import SetVariables

class TestSetVariables(unittest.TestCase):
    """SetVariables unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetVariables:
        """Test SetVariables
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetVariables`
        """
        model = SetVariables()
        if include_optional:
            return SetVariables(
                output_mapping = '0',
                post_actions = [
                    None
                    ],
                post_actions_ids = [
                    ''
                    ],
                namespace = '0',
                output_schema = openapi_client.models.output_schema.outputSchema()
            )
        else:
            return SetVariables(
        )
        """

    def testSetVariables(self):
        """Test SetVariables"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
