# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.customer_reference5 import CustomerReference5

class TestCustomerReference5(unittest.TestCase):
    """CustomerReference5 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerReference5:
        """Test CustomerReference5
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerReference5`
        """
        model = CustomerReference5()
        if include_optional:
            return CustomerReference5(
                source_channel_id = '',
                source_tenant_id = '0',
                source_customer_id = '0',
                first_name = '',
                last_name = '',
                phone = '',
                email = ''
            )
        else:
            return CustomerReference5(
                source_channel_id = '',
                source_tenant_id = '0',
                source_customer_id = '0',
                email = '',
        )
        """

    def testCustomerReference5(self):
        """Test CustomerReference5"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
