# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.payment_method_refund_wallet_action_details import PaymentMethodRefundWalletActionDetails

class TestPaymentMethodRefundWalletActionDetails(unittest.TestCase):
    """PaymentMethodRefundWalletActionDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentMethodRefundWalletActionDetails:
        """Test PaymentMethodRefundWalletActionDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentMethodRefundWalletActionDetails`
        """
        model = PaymentMethodRefundWalletActionDetails()
        if include_optional:
            return PaymentMethodRefundWalletActionDetails(
                wallet_action_id = '',
                funding_transaction_id = ''
            )
        else:
            return PaymentMethodRefundWalletActionDetails(
        )
        """

    def testPaymentMethodRefundWalletActionDetails(self):
        """Test PaymentMethodRefundWalletActionDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
