# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.wallet_action_wallet_action_service_v1_rise_wallet_actions_wallet_action_id_disable_post_disable_wallet_action_request_body import WalletActionWalletActionServiceV1RiseWalletActionsWalletActionIdDisablePostDisableWalletActionRequestBody

class TestWalletActionWalletActionServiceV1RiseWalletActionsWalletActionIdDisablePostDisableWalletActionRequestBody(unittest.TestCase):
    """WalletActionWalletActionServiceV1RiseWalletActionsWalletActionIdDisablePostDisableWalletActionRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WalletActionWalletActionServiceV1RiseWalletActionsWalletActionIdDisablePostDisableWalletActionRequestBody:
        """Test WalletActionWalletActionServiceV1RiseWalletActionsWalletActionIdDisablePostDisableWalletActionRequestBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WalletActionWalletActionServiceV1RiseWalletActionsWalletActionIdDisablePostDisableWalletActionRequestBody`
        """
        model = WalletActionWalletActionServiceV1RiseWalletActionsWalletActionIdDisablePostDisableWalletActionRequestBody()
        if include_optional:
            return WalletActionWalletActionServiceV1RiseWalletActionsWalletActionIdDisablePostDisableWalletActionRequestBody(
                revision = ''
            )
        else:
            return WalletActionWalletActionServiceV1RiseWalletActionsWalletActionIdDisablePostDisableWalletActionRequestBody(
                revision = '',
        )
        """

    def testWalletActionWalletActionServiceV1RiseWalletActionsWalletActionIdDisablePostDisableWalletActionRequestBody(self):
        """Test WalletActionWalletActionServiceV1RiseWalletActionsWalletActionIdDisablePostDisableWalletActionRequestBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
