# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_recipient_request import GetRecipientRequest

class TestGetRecipientRequest(unittest.TestCase):
    """GetRecipientRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRecipientRequest:
        """Test GetRecipientRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRecipientRequest`
        """
        model = GetRecipientRequest()
        if include_optional:
            return GetRecipientRequest(
                recipient_id = ''
            )
        else:
            return GetRecipientRequest(
        )
        """

    def testGetRecipientRequest(self):
        """Test GetRecipientRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
