# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.value1 import Value1

class TestValue1(unittest.TestCase):
    """Value1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Value1:
        """Test Value1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Value1`
        """
        model = Value1()
        if include_optional:
            return Value1(
                null_value = 'NULL_VALUE',
                number_value = 1.337,
                string_value = '',
                bool_value = True,
                struct_value = openapi_client.models.struct_value.structValue(),
                list_value = openapi_client.models.list_value_list_value.listValue_listValue(
                    values = [
                        None
                        ], )
            )
        else:
            return Value1(
        )
        """

    def testValue1(self):
        """Test Value1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
