# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.gift_card1 import GiftCard1

class TestGiftCard1(unittest.TestCase):
    """GiftCard1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GiftCard1:
        """Test GiftCard1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GiftCard1`
        """
        model = GiftCard1()
        if include_optional:
            return GiftCard1(
                id = '',
                code = '01234567',
                initial_value = '',
                balance = '',
                source_info = openapi_client.models.gift_card_source_info.GiftCardSourceInfo(
                    type = 'ORDER', 
                    source_tenant_id = '0', 
                    source_channel_id = '', 
                    source_location_id = '0', 
                    initiator = openapi_client.models.action_initiator.ActionInitiator(
                        type = 'APP', 
                        id = '', ), ),
                revision = '',
                currency = '',
                expiration_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_transaction_id = '',
                disable_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                idempotency_key = '0',
                code_suffix = '',
                transaction_details = openapi_client.models.transaction_details.TransactionDetails(
                    last_transaction = openapi_client.models.transaction_wrapper.TransactionWrapper(
                        id = '', 
                        created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                    last_decreasing_transaction = openapi_client.models.transaction_wrapper.TransactionWrapper(
                        id = '', 
                        created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                    last_increasing_transaction = openapi_client.models.transaction_wrapper.TransactionWrapper(
                        id = '', 
                        created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), )
            )
        else:
            return GiftCard1(
        )
        """

    def testGiftCard1(self):
        """Test GiftCard1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
