# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.transaction3 import Transaction3

class TestTransaction3(unittest.TestCase):
    """Transaction3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Transaction3:
        """Test Transaction3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Transaction3`
        """
        model = Transaction3()
        if include_optional:
            return Transaction3(
                id = '',
                created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                type = '{\"order\":1,\"value\":\"REDEEM\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}',
                gift_card_id = '',
                amount = '',
                operation_type = '{\"order\":0,\"value\":\"ADD\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}',
                idempotency_key = '0',
                updated_balance = '',
                source_info = openapi_client.models.transaction_source_info.TransactionSourceInfo(
                    initiator = openapi_client.models.action_initiator.ActionInitiator(
                        type = '{\"order\":1,\"value\":\"APP\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', 
                        id = '', ), 
                    source_tenant_id = '0', 
                    source_channel_id = '', 
                    source_location_id = '0', ),
                external_event = openapi_client.models.external_event.ExternalEvent(
                    name = '{\"order\":1,\"value\":\"ORDER\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', 
                    description = '0', ),
                external_id = '',
                redeem_options = openapi_client.models.redeem_options.RedeemOptions(
                    redeem_options = openapi_client.models.redeem_options.RedeemOptions(), ),
                void_options = openapi_client.models.void_options.VoidOptions(
                    void_options = openapi_client.models.void_options.VoidOptions(), ),
                reward_options = openapi_client.models.reward_options.RewardOptions(
                    reward_options = openapi_client.models.reward_options.RewardOptions(), ),
                wallet_action_end_options = openapi_client.models.wallet_action_end_options.WalletActionEndOptions(
                    wallet_action_end_options = openapi_client.models.wallet_action_end_options.WalletActionEndOptions(), ),
                campaign_options = openapi_client.models.campaign_options.CampaignOptions(
                    campaign_options = openapi_client.models.campaign_options.CampaignOptions(), ),
                store_credit_refund_options = openapi_client.models.store_credit_refund_options.StoreCreditRefundOptions(
                    store_credit_refund_options = openapi_client.models.store_credit_refund_options.StoreCreditRefundOptions(), ),
                migration_options = openapi_client.models.migration_options.MigrationOptions(
                    migration_options = openapi_client.models.migration_options.MigrationOptions(), ),
                payment_method_refund_options = openapi_client.models.payment_method_refund_options.PaymentMethodRefundOptions(
                    payment_method_refund_options = openapi_client.models.payment_method_refund_options.PaymentMethodRefundOptions(), ),
                initial_options = openapi_client.models.initial_options.InitialOptions(
                    initial_options = openapi_client.models.initial_options.InitialOptions(), ),
                wallet_action_start_options = openapi_client.models.wallet_action_start_options.WalletActionStartOptions(
                    wallet_action_start_options = openapi_client.models.wallet_action_start_options.WalletActionStartOptions(), ),
                bulk_options = openapi_client.models.bulk_options.BulkOptions(
                    bulk_options = openapi_client.models.bulk_options.BulkOptions(), ),
                manual_options = openapi_client.models.manual_options.ManualOptions(
                    manual_options = openapi_client.models.manual_options.ManualOptions(), )
            )
        else:
            return Transaction3(
                type = '{\"order\":1,\"value\":\"REDEEM\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}',
                gift_card_id = '',
                amount = '',
        )
        """

    def testTransaction3(self):
        """Test Transaction3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
