# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.create_wallet_action_by_customer_reference_response1 import CreateWalletActionByCustomerReferenceResponse1

class TestCreateWalletActionByCustomerReferenceResponse1(unittest.TestCase):
    """CreateWalletActionByCustomerReferenceResponse1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateWalletActionByCustomerReferenceResponse1:
        """Test CreateWalletActionByCustomerReferenceResponse1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateWalletActionByCustomerReferenceResponse1`
        """
        model = CreateWalletActionByCustomerReferenceResponse1()
        if include_optional:
            return CreateWalletActionByCustomerReferenceResponse1(
                wallet_action = openapi_client.models.wallet_action.WalletAction(
                    id = '', 
                    revision = '', 
                    created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    expiration_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    disable_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    amount = '', 
                    note = '', 
                    type = '{\"order\":0,\"value\":\"UNKNOWN\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', 
                    wallet_action_started = openapi_client.models.wallet_action_execution_details.WalletActionExecutionDetails(
                        transaction_id = '', 
                        execution_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                    wallet_action_ended = openapi_client.models.wallet_action_execution_details.WalletActionExecutionDetails(
                        transaction_id = '', 
                        execution_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), 
                    status = '{\"order\":0,\"value\":\"PENDING\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', 
                    source = openapi_client.models.action_initiator.ActionInitiator(
                        type = '{\"order\":1,\"value\":\"APP\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', 
                        id = '', ), 
                    notifications = openapi_client.models.notifications.Notifications(
                        email_params = openapi_client.models.email_params.EmailParams(
                            skip_email_dispatch = True, 
                            override_template_id = '', ), ), 
                    liability = True, 
                    store_credit_context = openapi_client.models.store_credit_context.StoreCreditContext(
                        issuer = '{\"order\":1,\"value\":\"WORKFLOW\",\"description\":\"Issued from a workflow\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', 
                        issuer_id = '0', 
                        note = '0', 
                        source_channel_id = '', 
                        source_tenant_id = '0', ), 
                    external_event = openapi_client.models.external_event.ExternalEvent(
                        name = '{\"order\":1,\"value\":\"ORDER\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', 
                        description = '0', ), 
                    wallet_id = '', 
                    idempotency_key = '0', ),
                wallet = openapi_client.models.wallet.Wallet(
                    id = '', 
                    revision = '', 
                    gift_card_id = '', 
                    customer_references = [
                        openapi_client.models.customer_reference.CustomerReference(
                            source_channel_id = '', 
                            source_tenant_id = '0', 
                            source_customer_id = '0', 
                            first_name = '', 
                            last_name = '', 
                            phone = '', 
                            email = '', )
                        ], 
                    created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    gift_card_info = openapi_client.models.gift_card_info.GiftCardInfo(
                        code = '0', 
                        balance = '', 
                        currency = '', 
                        code_suffix = '', ), 
                    primary_contact_details = openapi_client.models.contact_details.ContactDetails(
                        email = '', 
                        phone = '', 
                        first_name = '', 
                        last_name = '', ), )
            )
        else:
            return CreateWalletActionByCustomerReferenceResponse1(
        )
        """

    def testCreateWalletActionByCustomerReferenceResponse1(self):
        """Test CreateWalletActionByCustomerReferenceResponse1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
