# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.query_orders_request import QueryOrdersRequest

class TestQueryOrdersRequest(unittest.TestCase):
    """QueryOrdersRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueryOrdersRequest:
        """Test QueryOrdersRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueryOrdersRequest`
        """
        model = QueryOrdersRequest()
        if include_optional:
            return QueryOrdersRequest(
                query = None
            )
        else:
            return QueryOrdersRequest(
        )
        """

    def testQueryOrdersRequest(self):
        """Test QueryOrdersRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
