# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.condition_filter import ConditionFilter

class TestConditionFilter(unittest.TestCase):
    """ConditionFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConditionFilter:
        """Test ConditionFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConditionFilter`
        """
        model = ConditionFilter()
        if include_optional:
            return ConditionFilter(
                condition_blocks = [
                    None
                    ],
                post_actions = [
                    None
                    ],
                post_actions_ids = [
                    ''
                    ],
                else_post_actions = [
                    None
                    ]
            )
        else:
            return ConditionFilter(
        )
        """

    def testConditionFilter(self):
        """Test ConditionFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
