# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.trigger import Trigger

class TestTrigger(unittest.TestCase):
    """Trigger unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Trigger:
        """Test Trigger
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Trigger`
        """
        model = Trigger()
        if include_optional:
            return Trigger(
                app_id = '',
                trigger_key = '0',
                filters = [
                    None
                    ],
                scheduled_event_offset = None,
                rate_limit = None,
                automation_config_mapping = openapi_client.models.automation_config_mapping.automationConfigMapping(),
                override_schema = openapi_client.models.override_schema.overrideSchema()
            )
        else:
            return Trigger(
        )
        """

    def testTrigger(self):
        """Test Trigger"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
