# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.bulk_report_event_response import BulkReportEventResponse

class TestBulkReportEventResponse(unittest.TestCase):
    """BulkReportEventResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkReportEventResponse:
        """Test BulkReportEventResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkReportEventResponse`
        """
        model = BulkReportEventResponse()
        if include_optional:
            return BulkReportEventResponse(
                trigger_key = '0',
                results = [
                    None
                    ],
                bulk_action_metadata = None
            )
        else:
            return BulkReportEventResponse(
        )
        """

    def testBulkReportEventResponse(self):
        """Test BulkReportEventResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
