# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.transaction1 import Transaction1

class TestTransaction1(unittest.TestCase):
    """Transaction1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Transaction1:
        """Test Transaction1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Transaction1`
        """
        model = Transaction1()
        if include_optional:
            return Transaction1(
                id = '',
                created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                type = 'REDEEM',
                gift_card_id = '',
                amount = '',
                operation_type = 'ADD',
                idempotency_key = '0',
                updated_balance = '',
                source_info = openapi_client.models.transaction_source_info.TransactionSourceInfo(
                    initiator = openapi_client.models.action_initiator.ActionInitiator(
                        type = 'APP', 
                        id = '', ), 
                    source_tenant_id = '0', 
                    source_channel_id = '', 
                    source_location_id = '0', ),
                external_event = openapi_client.models.external_event.ExternalEvent(
                    name = 'ORDER', 
                    description = '0', ),
                external_id = '',
                redeem_options = openapi_client.models.redeem_options_redeem_options.RedeemOptions_redeemOptions(
                    order_id = '', 
                    liability = True, 
                    total_price = '', 
                    order_number = '', ),
                void_options = openapi_client.models.void_options_void_options.VoidOptions_voidOptions(
                    transaction_id = '', ),
                reward_options = openapi_client.models.reward_options_reward_options.RewardOptions_rewardOptions(
                    wallet_action_id = '', 
                    liability = True, ),
                wallet_action_end_options = openapi_client.models.wallet_action_end_options_wallet_action_end_options.WalletActionEndOptions_walletActionEndOptions(
                    wallet_action_id = '', 
                    transaction_id = '', 
                    liability = True, 
                    reason = 'CANCEL', ),
                campaign_options = openapi_client.models.campaign_options_campaign_options.CampaignOptions_campaignOptions(
                    campaign_id = '', 
                    liability = True, ),
                store_credit_refund_options = openapi_client.models.store_credit_refund_options_store_credit_refund_options.StoreCreditRefundOptions_storeCreditRefundOptions(
                    wallet_action_id = '', 
                    liability = True, ),
                migration_options = openapi_client.models.migration_options_migration_options.MigrationOptions_migrationOptions(
                    previous_id = '', 
                    liability = True, 
                    note = '', ),
                payment_method_refund_options = openapi_client.models.payment_method_refund_options_payment_method_refund_options.PaymentMethodRefundOptions_paymentMethodRefundOptions(
                    order_id = '', 
                    liability = True, 
                    order_number = '', 
                    active_funding_transaction = openapi_client.models.payment_method_refund_wallet_action_details.PaymentMethodRefundWalletActionDetails(
                        wallet_action_id = '', 
                        funding_transaction_id = '', ), ),
                initial_options = openapi_client.models.initial_options_initial_options.InitialOptions_initialOptions(
                    gift_card_type = 'ORDER', ),
                wallet_action_start_options = openapi_client.models.wallet_action_start_options_wallet_action_start_options.WalletActionStartOptions_walletActionStartOptions(
                    wallet_action_id = '', 
                    liability = True, 
                    context = openapi_client.models.store_credit_context.StoreCreditContext(
                        issuer = 'WORKFLOW', 
                        issuer_id = '0', 
                        note = '0', 
                        source_channel_id = '', 
                        source_tenant_id = '0', ), ),
                bulk_options = openapi_client.models.bulk_options_bulk_options.BulkOptions_bulkOptions(
                    bulk_id = '', 
                    liability = True, 
                    note = '0', ),
                manual_options = openapi_client.models.manual_options_manual_options.ManualOptions_manualOptions(
                    note = '', )
            )
        else:
            return Transaction1(
        )
        """

    def testTransaction1(self):
        """Test Transaction1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
