# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.kind1 import Kind1

class TestKind1(unittest.TestCase):
    """Kind1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Kind1:
        """Test Kind1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Kind1`
        """
        model = Kind1()
        if include_optional:
            return Kind1(
                value = openapi_client.models.options.options(
                    include_options = openapi_client.models.include_missing_values_options.IncludeMissingValuesOptions(
                        add_to_bucket = '', ), )
            )
        else:
            return Kind1(
        )
        """

    def testKind1(self):
        """Test Kind1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
