# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.invalidcode_details_application_error import INVALIDCODEDetailsApplicationError

class TestINVALIDCODEDetailsApplicationError(unittest.TestCase):
    """INVALIDCODEDetailsApplicationError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> INVALIDCODEDetailsApplicationError:
        """Test INVALIDCODEDetailsApplicationError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `INVALIDCODEDetailsApplicationError`
        """
        model = INVALIDCODEDetailsApplicationError()
        if include_optional:
            return INVALIDCODEDetailsApplicationError(
                code = 'INVALID_CODE',
                description = '',
                data = None
            )
        else:
            return INVALIDCODEDetailsApplicationError(
                code = 'INVALID_CODE',
                description = '',
        )
        """

    def testINVALIDCODEDetailsApplicationError(self):
        """Test INVALIDCODEDetailsApplicationError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
