# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.bulk_options1 import BulkOptions1

class TestBulkOptions1(unittest.TestCase):
    """BulkOptions1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkOptions1:
        """Test BulkOptions1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkOptions1`
        """
        model = BulkOptions1()
        if include_optional:
            return BulkOptions1(
                bulk_options = openapi_client.models.bulk_options.BulkOptions(
                    bulk_options = openapi_client.models.bulk_options.BulkOptions(), )
            )
        else:
            return BulkOptions1(
        )
        """

    def testBulkOptions1(self):
        """Test BulkOptions1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
