# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.report_domain_event_request import ReportDomainEventRequest

class TestReportDomainEventRequest(unittest.TestCase):
    """ReportDomainEventRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReportDomainEventRequest:
        """Test ReportDomainEventRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReportDomainEventRequest`
        """
        model = ReportDomainEventRequest()
        if include_optional:
            return ReportDomainEventRequest(
                trigger_app_id = '',
                report_event_request = None
            )
        else:
            return ReportDomainEventRequest(
        )
        """

    def testReportDomainEventRequest(self):
        """Test ReportDomainEventRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
