# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.wallet2 import Wallet2

class TestWallet2(unittest.TestCase):
    """Wallet2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Wallet2:
        """Test Wallet2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Wallet2`
        """
        model = Wallet2()
        if include_optional:
            return Wallet2(
                id = '',
                revision = '',
                gift_card_id = '',
                customer_references = [
                    openapi_client.models.customer_reference.CustomerReference(
                        source_channel_id = '', 
                        source_tenant_id = '0', 
                        source_customer_id = '0', 
                        first_name = '', 
                        last_name = '', 
                        phone = '', 
                        email = '', )
                    ],
                created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                gift_card_info = openapi_client.models.gift_card_info.GiftCardInfo(
                    code = '0', 
                    balance = '', 
                    currency = '', 
                    code_suffix = '', ),
                primary_contact_details = openapi_client.models.contact_details.ContactDetails(
                    email = '', 
                    phone = '', 
                    first_name = '', 
                    last_name = '', )
            )
        else:
            return Wallet2(
        )
        """

    def testWallet2(self):
        """Test Wallet2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
