# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.wallet_action_with_balance import WalletActionWithBalance

class TestWalletActionWithBalance(unittest.TestCase):
    """WalletActionWithBalance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WalletActionWithBalance:
        """Test WalletActionWithBalance
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WalletActionWithBalance`
        """
        model = WalletActionWithBalance()
        if include_optional:
            return WalletActionWithBalance(
                wallet_action = None,
                balance = ''
            )
        else:
            return WalletActionWithBalance(
        )
        """

    def testWalletActionWithBalance(self):
        """Test WalletActionWithBalance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
