# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.action_completed_request import ActionCompletedRequest

class TestActionCompletedRequest(unittest.TestCase):
    """ActionCompletedRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ActionCompletedRequest:
        """Test ActionCompletedRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ActionCompletedRequest`
        """
        model = ActionCompletedRequest()
        if include_optional:
            return ActionCompletedRequest(
                execution_identifier = '',
                result = openapi_client.models.result.result()
            )
        else:
            return ActionCompletedRequest(
        )
        """

    def testActionCompletedRequest(self):
        """Test ActionCompletedRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
