# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.bulk_cancel_event_response import BulkCancelEventResponse

class TestBulkCancelEventResponse(unittest.TestCase):
    """BulkCancelEventResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BulkCancelEventResponse:
        """Test BulkCancelEventResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BulkCancelEventResponse`
        """
        model = BulkCancelEventResponse()
        if include_optional:
            return BulkCancelEventResponse(
                trigger_key = '0',
                results = [
                    None
                    ],
                bulk_action_metadata = None
            )
        else:
            return BulkCancelEventResponse(
        )
        """

    def testBulkCancelEventResponse(self):
        """Test BulkCancelEventResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
