# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.filter4 import Filter4

class TestFilter4(unittest.TestCase):
    """Filter4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Filter4:
        """Test Filter4
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Filter4`
        """
        model = Filter4()
        if include_optional:
            return Filter4(
                fields = openapi_client.models.fields.fields(
                    key = '', 
                    value = openapi_client.models.value.Value(), )
            )
        else:
            return Filter4(
        )
        """

    def testFilter4(self):
        """Test Filter4"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
