# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AggregationType(str, Enum):
    """
    
    """

    """
    allowed enum values
    """
    VALUE = 'VALUE'
    RANGE = 'RANGE'
    SCALAR = 'SCALAR'
    DATE_HISTOGRAM = 'DATE_HISTOGRAM'
    NESTED = 'NESTED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AggregationType from a JSON string"""
        return cls(json.loads(json_str))


