# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class BillingInfo(BaseModel):
    """
    Information about the billing address of the buyer.
    """ # noqa: E501
    address1: Optional[Annotated[str, Field(strict=True, max_length=150)]] = Field(default=None, description="The street address of the billing address.")
    address2: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, description="An optional additional field for the street address of the billing address.address")
    city: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, description="The city of the billing address.")
    company: Optional[Annotated[str, Field(strict=True, max_length=500)]] = Field(default=None, description="The company of the person associated with the billing address.")
    country: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, description="The name of the country of the billing address.")
    state: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, description="The name of the region of the billing address.")
    zip: Optional[Annotated[str, Field(strict=True, max_length=20)]] = Field(default=None, description="The postal code of the billing address.")
    state_code: Optional[Annotated[str, Field(strict=True, max_length=20)]] = Field(default=None, description="province code of the billing address.", alias="stateCode")
    country_code: Optional[Annotated[str, Field(strict=True, max_length=10)]] = Field(default=None, description="country code of the billing address.", alias="countryCode")
    latitude: Optional[Annotated[str, Field(strict=True, max_length=30)]] = Field(default=None, description="The latitude of the billing address.")
    longitude: Optional[Annotated[str, Field(strict=True, max_length=30)]] = Field(default=None, description="The longitude of the billing address.")
    __properties: ClassVar[List[str]] = ["address1", "address2", "city", "company", "country", "state", "zip", "stateCode", "countryCode", "latitude", "longitude"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BillingInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BillingInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address1": obj.get("address1"),
            "address2": obj.get("address2"),
            "city": obj.get("city"),
            "company": obj.get("company"),
            "country": obj.get("country"),
            "state": obj.get("state"),
            "zip": obj.get("zip"),
            "stateCode": obj.get("stateCode"),
            "countryCode": obj.get("countryCode"),
            "latitude": obj.get("latitude"),
            "longitude": obj.get("longitude")
        })
        return _obj


