# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class ConditionAction(BaseModel):
    """
    
    """ # noqa: E501
    or_expression_groups: Optional[Annotated[List[Dict[str, Any]], Field(min_length=1, max_length=10)]] = Field(default=None, description="The condition evaluates to `true` if either of the expression groups evaluate to `true`.", alias="orExpressionGroups")
    true_post_action_ids: Optional[Annotated[List[StrictStr], Field(max_length=20)]] = Field(default=None, description="List of IDs of actions to run when the entire condition is evaluated to `true`.", alias="truePostActionIds")
    false_post_action_ids: Optional[Annotated[List[StrictStr], Field(max_length=20)]] = Field(default=None, description="List of IDs of actions to run when the entire condition is evaluated to `false`.", alias="falsePostActionIds")
    __properties: ClassVar[List[str]] = ["orExpressionGroups", "truePostActionIds", "falsePostActionIds"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConditionAction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConditionAction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "orExpressionGroups": obj.get("orExpressionGroups"),
            "truePostActionIds": obj.get("truePostActionIds"),
            "falsePostActionIds": obj.get("falsePostActionIds")
        })
        return _obj


