# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ExecuteFromActionRequest(BaseModel):
    """
    
    """ # noqa: E501
    action_id: Optional[StrictStr] = Field(default=None, description="Requested action id", alias="actionId")
    activation_id: Optional[StrictStr] = Field(default=None, description="Optional: an activation id to link this action to", alias="activationId")
    payload: Optional[Dict[str, Any]] = Field(default=None, description="Activation payload")
    configuration_correlation_id: Optional[StrictStr] = Field(default=None, description="Configuration correlation id to run this action from", alias="configurationCorrelationId")
    schedule_id: Optional[StrictStr] = Field(default=None, description="Optional - schedule id that this action was scheduled from", alias="scheduleId")
    external_entity_id: Optional[StrictStr] = Field(default=None, description="Optional - an external entity id that this execution is related to", alias="externalEntityId")
    automation: Optional[Dict[str, Any]] = Field(default=None, description="Optional - Activation automation")
    __properties: ClassVar[List[str]] = ["actionId", "activationId", "payload", "configurationCorrelationId", "scheduleId", "externalEntityId", "automation"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExecuteFromActionRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExecuteFromActionRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "actionId": obj.get("actionId"),
            "activationId": obj.get("activationId"),
            "payload": obj.get("payload"),
            "configurationCorrelationId": obj.get("configurationCorrelationId"),
            "scheduleId": obj.get("scheduleId"),
            "externalEntityId": obj.get("externalEntityId"),
            "automation": obj.get("automation")
        })
        return _obj


