# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_client.models.fixed_date import FixedDate
from openapi_client.models.relative_expires_at import RelativeExpiresAt
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

EXPIRATION1_ONE_OF_SCHEMAS = ["FixedDate", "RelativeExpiresAt"]

class Expiration1(BaseModel):
    """
    The expiration date to apply to the Gift Card.
    """
    # data type: FixedDate
    oneof_schema_1_validator: Optional[FixedDate] = None
    # data type: RelativeExpiresAt
    oneof_schema_2_validator: Optional[RelativeExpiresAt] = None
    actual_instance: Optional[Union[FixedDate, RelativeExpiresAt]] = None
    one_of_schemas: Set[str] = { "FixedDate", "RelativeExpiresAt" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = Expiration1.model_construct()
        error_messages = []
        match = 0
        # validate data type: FixedDate
        if not isinstance(v, FixedDate):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FixedDate`")
        else:
            match += 1
        # validate data type: RelativeExpiresAt
        if not isinstance(v, RelativeExpiresAt):
            error_messages.append(f"Error! Input type `{type(v)}` is not `RelativeExpiresAt`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in Expiration1 with oneOf schemas: FixedDate, RelativeExpiresAt. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in Expiration1 with oneOf schemas: FixedDate, RelativeExpiresAt. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into FixedDate
        try:
            instance.actual_instance = FixedDate.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into RelativeExpiresAt
        try:
            instance.actual_instance = RelativeExpiresAt.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into Expiration1 with oneOf schemas: FixedDate, RelativeExpiresAt. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into Expiration1 with oneOf schemas: FixedDate, RelativeExpiresAt. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], FixedDate, RelativeExpiresAt]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


