# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class GiftCardOrder(BaseModel):
    """
    A Gift Card Order is a reflection of an order in a Sales Channel that includes a Gift Card.
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Order ID.")
    revision: Optional[StrictStr] = Field(default=None, description="Revision number, which increments by 1 each time the Order is updated. To prevent conflicting changes, the current revision must be passed when updating the Order.  Ignored when creating a Order.")
    created_date: Optional[datetime] = Field(default=None, description="Date and time the Order was created.", alias="createdDate")
    updated_date: Optional[datetime] = Field(default=None, description="Date and time the Order was last updated.", alias="updatedDate")
    source_channel_id: Optional[StrictStr] = Field(default=None, description="Source sales channel, i.e. Shopify.", alias="sourceChannelId")
    source_tenant_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=50)]] = Field(default=None, description="Tenant ID in source sales channel, i.e. shop ID.", alias="sourceTenantId")
    source_order_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=50)]] = Field(default=None, description="Order ID in source sales channel.", alias="sourceOrderId")
    source_order_number: Optional[Annotated[str, Field(strict=True, max_length=50)]] = Field(default=None, description="The order number in source sales channel.", alias="sourceOrderNumber")
    total_amount: Optional[StrictStr] = Field(default=None, description="The total amount of the order that contains the Gift Card.", alias="totalAmount")
    currency: Optional[StrictStr] = Field(default=None, description="The order's currency.")
    note: Optional[Annotated[str, Field(strict=True, max_length=500)]] = Field(default=None, description="Note to be added to the order.")
    payment_status: Optional[StrictStr] = Field(default=None, description="The payment status of the order.", alias="paymentStatus")
    fulfillment_status: Optional[StrictStr] = Field(default=None, description="Fulfillment status of the order in Rise.", alias="fulfillmentStatus")
    status: Optional[StrictStr] = Field(default=None, description="Status of the order in Rise.")
    buyer_info: Optional[Dict[str, Any]] = Field(default=None, description="Information about the buyer.", alias="buyerInfo")
    schedule_fulfill_at: Optional[datetime] = Field(default=None, description="Date and time to fulfill the order by creating Gift Cards. Default is now.", alias="scheduleFulfillAt")
    rise_fulfilled_at: Optional[datetime] = Field(default=None, description="Date and time the order was fulfilled in Rise by creating Gift Cards.", alias="riseFulfilledAt")
    source_fulfilled_at: Optional[datetime] = Field(default=None, description="Date and time the order was marked fulfilled in the Source sales channel.", alias="sourceFulfilledAt")
    line_items: Optional[Annotated[List[Dict[str, Any]], Field(max_length=100)]] = Field(default=None, description="The line items in the order that are Gift Cards.", alias="lineItems")
    fraud_message: Optional[Annotated[str, Field(strict=True, max_length=250)]] = Field(default=None, description="The fraud message.", alias="fraudMessage")
    fraud_type: Optional[StrictStr] = Field(default=None, description="The fraud logic type.", alias="fraudType")
    source_location_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=50)]] = Field(default=None, description="Location ID in Source.", alias="sourceLocationId")
    __properties: ClassVar[List[str]] = ["id", "revision", "createdDate", "updatedDate", "sourceChannelId", "sourceTenantId", "sourceOrderId", "sourceOrderNumber", "totalAmount", "currency", "note", "paymentStatus", "fulfillmentStatus", "status", "buyerInfo", "scheduleFulfillAt", "riseFulfilledAt", "sourceFulfilledAt", "lineItems", "fraudMessage", "fraudType", "sourceLocationId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GiftCardOrder from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "revision",
            "created_date",
            "updated_date",
            "rise_fulfilled_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GiftCardOrder from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "revision": obj.get("revision"),
            "createdDate": obj.get("createdDate"),
            "updatedDate": obj.get("updatedDate"),
            "sourceChannelId": obj.get("sourceChannelId"),
            "sourceTenantId": obj.get("sourceTenantId"),
            "sourceOrderId": obj.get("sourceOrderId"),
            "sourceOrderNumber": obj.get("sourceOrderNumber"),
            "totalAmount": obj.get("totalAmount"),
            "currency": obj.get("currency"),
            "note": obj.get("note"),
            "paymentStatus": obj.get("paymentStatus"),
            "fulfillmentStatus": obj.get("fulfillmentStatus"),
            "status": obj.get("status"),
            "buyerInfo": obj.get("buyerInfo"),
            "scheduleFulfillAt": obj.get("scheduleFulfillAt"),
            "riseFulfilledAt": obj.get("riseFulfilledAt"),
            "sourceFulfilledAt": obj.get("sourceFulfilledAt"),
            "lineItems": obj.get("lineItems"),
            "fraudMessage": obj.get("fraudMessage"),
            "fraudType": obj.get("fraudType"),
            "sourceLocationId": obj.get("sourceLocationId")
        })
        return _obj


