# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_client.models.bulk_options import BulkOptions
from openapi_client.models.campaign_options import CampaignOptions
from openapi_client.models.manual_options import ManualOptions
from openapi_client.models.migration_options import MigrationOptions
from openapi_client.models.order_options import OrderOptions
from openapi_client.models.store_credit_options import StoreCreditOptions
from openapi_client.models.workflow_options import WorkflowOptions
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

GIFTCARDSOURCEINFO2_ONE_OF_SCHEMAS = ["BulkOptions", "CampaignOptions", "ManualOptions", "MigrationOptions", "OrderOptions", "StoreCreditOptions", "WorkflowOptions"]

class GiftCardSourceInfo2(BaseModel):
    """
    Information about the source of the gift card.
    """
    # data type: OrderOptions
    oneof_schema_1_validator: Optional[OrderOptions] = None
    # data type: CampaignOptions
    oneof_schema_2_validator: Optional[CampaignOptions] = None
    # data type: MigrationOptions
    oneof_schema_3_validator: Optional[MigrationOptions] = None
    # data type: StoreCreditOptions
    oneof_schema_4_validator: Optional[StoreCreditOptions] = None
    # data type: WorkflowOptions
    oneof_schema_5_validator: Optional[WorkflowOptions] = None
    # data type: BulkOptions
    oneof_schema_6_validator: Optional[BulkOptions] = None
    # data type: ManualOptions
    oneof_schema_7_validator: Optional[ManualOptions] = None
    actual_instance: Optional[Union[BulkOptions, CampaignOptions, ManualOptions, MigrationOptions, OrderOptions, StoreCreditOptions, WorkflowOptions]] = None
    one_of_schemas: Set[str] = { "BulkOptions", "CampaignOptions", "ManualOptions", "MigrationOptions", "OrderOptions", "StoreCreditOptions", "WorkflowOptions" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = GiftCardSourceInfo2.model_construct()
        error_messages = []
        match = 0
        # validate data type: OrderOptions
        if not isinstance(v, OrderOptions):
            error_messages.append(f"Error! Input type `{type(v)}` is not `OrderOptions`")
        else:
            match += 1
        # validate data type: CampaignOptions
        if not isinstance(v, CampaignOptions):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CampaignOptions`")
        else:
            match += 1
        # validate data type: MigrationOptions
        if not isinstance(v, MigrationOptions):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MigrationOptions`")
        else:
            match += 1
        # validate data type: StoreCreditOptions
        if not isinstance(v, StoreCreditOptions):
            error_messages.append(f"Error! Input type `{type(v)}` is not `StoreCreditOptions`")
        else:
            match += 1
        # validate data type: WorkflowOptions
        if not isinstance(v, WorkflowOptions):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkflowOptions`")
        else:
            match += 1
        # validate data type: BulkOptions
        if not isinstance(v, BulkOptions):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BulkOptions`")
        else:
            match += 1
        # validate data type: ManualOptions
        if not isinstance(v, ManualOptions):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ManualOptions`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in GiftCardSourceInfo2 with oneOf schemas: BulkOptions, CampaignOptions, ManualOptions, MigrationOptions, OrderOptions, StoreCreditOptions, WorkflowOptions. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in GiftCardSourceInfo2 with oneOf schemas: BulkOptions, CampaignOptions, ManualOptions, MigrationOptions, OrderOptions, StoreCreditOptions, WorkflowOptions. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into OrderOptions
        try:
            instance.actual_instance = OrderOptions.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CampaignOptions
        try:
            instance.actual_instance = CampaignOptions.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into MigrationOptions
        try:
            instance.actual_instance = MigrationOptions.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into StoreCreditOptions
        try:
            instance.actual_instance = StoreCreditOptions.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WorkflowOptions
        try:
            instance.actual_instance = WorkflowOptions.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into BulkOptions
        try:
            instance.actual_instance = BulkOptions.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ManualOptions
        try:
            instance.actual_instance = ManualOptions.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into GiftCardSourceInfo2 with oneOf schemas: BulkOptions, CampaignOptions, ManualOptions, MigrationOptions, OrderOptions, StoreCreditOptions, WorkflowOptions. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into GiftCardSourceInfo2 with oneOf schemas: BulkOptions, CampaignOptions, ManualOptions, MigrationOptions, OrderOptions, StoreCreditOptions, WorkflowOptions. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], BulkOptions, CampaignOptions, ManualOptions, MigrationOptions, OrderOptions, StoreCreditOptions, WorkflowOptions]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


