# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class GiftCard(BaseModel):
    """
    GiftCard is the main entity of GiftCardService. It contains basic information such as gift card code, balance, and expiration date, as well as information about the source of the gift card (e.g., purchase, migration, etc.).
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="Unique ID of the Gift Card.")
    code: Optional[Annotated[str, Field(min_length=8, strict=True, max_length=20)]] = Field(default=None, description="Gift Card code for redemption.")
    initial_value: Optional[StrictStr] = Field(default=None, description="Initial value of the Gift Card.", alias="initialValue")
    balance: Optional[StrictStr] = Field(default=None, description="Current balance of the Gift Card.")
    source_info: Optional[Dict[str, Any]] = Field(default=None, description="Information about the source of the gift card.", alias="sourceInfo")
    revision: Optional[StrictStr] = Field(default=None, description="Gift Card revision.")
    currency: Optional[StrictStr] = Field(default=None, description="Gift Card currency.")
    expiration_date: Optional[datetime] = Field(default=None, description="Gift Card expiration date.", alias="expirationDate")
    created_date: Optional[datetime] = Field(default=None, description="Gift Card creation date.", alias="createdDate")
    updated_date: Optional[datetime] = Field(default=None, description="Gift Card last update date.", alias="updatedDate")
    last_transaction_id: Optional[StrictStr] = Field(default=None, description="ID of the last transaction that modified the gift card balance.", alias="lastTransactionId")
    disable_date: Optional[datetime] = Field(default=None, description="Gift Card disable date, if the gift card was disabled.", alias="disableDate")
    idempotency_key: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=100)]] = Field(default=None, description="Gift Card idempotency key, to prevent duplicate creation.", alias="idempotencyKey")
    code_suffix: Optional[Annotated[str, Field(strict=True, max_length=4)]] = Field(default=None, description="Last 4 characters of the gift card code for easier reference and searching.", alias="codeSuffix")
    transaction_details: Optional[Dict[str, Any]] = Field(default=None, description="Transaction details related to the gift card.", alias="transactionDetails")
    __properties: ClassVar[List[str]] = ["id", "code", "initialValue", "balance", "sourceInfo", "revision", "currency", "expirationDate", "createdDate", "updatedDate", "lastTransactionId", "disableDate", "idempotencyKey", "codeSuffix", "transactionDetails"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GiftCard from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "balance",
            "revision",
            "created_date",
            "updated_date",
            "last_transaction_id",
            "disable_date",
            "code_suffix",
            "transaction_details",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GiftCard from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "code": obj.get("code"),
            "initialValue": obj.get("initialValue"),
            "balance": obj.get("balance"),
            "sourceInfo": obj.get("sourceInfo"),
            "revision": obj.get("revision"),
            "currency": obj.get("currency"),
            "expirationDate": obj.get("expirationDate"),
            "createdDate": obj.get("createdDate"),
            "updatedDate": obj.get("updatedDate"),
            "lastTransactionId": obj.get("lastTransactionId"),
            "disableDate": obj.get("disableDate"),
            "idempotencyKey": obj.get("idempotencyKey"),
            "codeSuffix": obj.get("codeSuffix"),
            "transactionDetails": obj.get("transactionDetails")
        })
        return _obj


