# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from openapi_client.models.bulk_options2 import BulkOptions2
from openapi_client.models.campaign_options2 import CampaignOptions2
from openapi_client.models.manual_options2 import ManualOptions2
from openapi_client.models.migration_options2 import MigrationOptions2
from openapi_client.models.order_options1 import OrderOptions1
from openapi_client.models.store_credit_options1 import StoreCreditOptions1
from openapi_client.models.workflow_options1 import WorkflowOptions1
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

GIFTCARDSOURCEINFO1_ONE_OF_SCHEMAS = ["BulkOptions2", "CampaignOptions2", "ManualOptions2", "MigrationOptions2", "OrderOptions1", "StoreCreditOptions1", "WorkflowOptions1"]

class GiftCardSourceInfo1(BaseModel):
    """
    Information about the source of the gift card.
    """
    # data type: OrderOptions1
    oneof_schema_1_validator: Optional[OrderOptions1] = None
    # data type: CampaignOptions2
    oneof_schema_2_validator: Optional[CampaignOptions2] = None
    # data type: MigrationOptions2
    oneof_schema_3_validator: Optional[MigrationOptions2] = None
    # data type: StoreCreditOptions1
    oneof_schema_4_validator: Optional[StoreCreditOptions1] = None
    # data type: WorkflowOptions1
    oneof_schema_5_validator: Optional[WorkflowOptions1] = None
    # data type: BulkOptions2
    oneof_schema_6_validator: Optional[BulkOptions2] = None
    # data type: ManualOptions2
    oneof_schema_7_validator: Optional[ManualOptions2] = None
    actual_instance: Optional[Union[BulkOptions2, CampaignOptions2, ManualOptions2, MigrationOptions2, OrderOptions1, StoreCreditOptions1, WorkflowOptions1]] = None
    one_of_schemas: Set[str] = { "BulkOptions2", "CampaignOptions2", "ManualOptions2", "MigrationOptions2", "OrderOptions1", "StoreCreditOptions1", "WorkflowOptions1" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = GiftCardSourceInfo1.model_construct()
        error_messages = []
        match = 0
        # validate data type: OrderOptions1
        if not isinstance(v, OrderOptions1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `OrderOptions1`")
        else:
            match += 1
        # validate data type: CampaignOptions2
        if not isinstance(v, CampaignOptions2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `CampaignOptions2`")
        else:
            match += 1
        # validate data type: MigrationOptions2
        if not isinstance(v, MigrationOptions2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `MigrationOptions2`")
        else:
            match += 1
        # validate data type: StoreCreditOptions1
        if not isinstance(v, StoreCreditOptions1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `StoreCreditOptions1`")
        else:
            match += 1
        # validate data type: WorkflowOptions1
        if not isinstance(v, WorkflowOptions1):
            error_messages.append(f"Error! Input type `{type(v)}` is not `WorkflowOptions1`")
        else:
            match += 1
        # validate data type: BulkOptions2
        if not isinstance(v, BulkOptions2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `BulkOptions2`")
        else:
            match += 1
        # validate data type: ManualOptions2
        if not isinstance(v, ManualOptions2):
            error_messages.append(f"Error! Input type `{type(v)}` is not `ManualOptions2`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in GiftCardSourceInfo1 with oneOf schemas: BulkOptions2, CampaignOptions2, ManualOptions2, MigrationOptions2, OrderOptions1, StoreCreditOptions1, WorkflowOptions1. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in GiftCardSourceInfo1 with oneOf schemas: BulkOptions2, CampaignOptions2, ManualOptions2, MigrationOptions2, OrderOptions1, StoreCreditOptions1, WorkflowOptions1. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into OrderOptions1
        try:
            instance.actual_instance = OrderOptions1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into CampaignOptions2
        try:
            instance.actual_instance = CampaignOptions2.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into MigrationOptions2
        try:
            instance.actual_instance = MigrationOptions2.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into StoreCreditOptions1
        try:
            instance.actual_instance = StoreCreditOptions1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into WorkflowOptions1
        try:
            instance.actual_instance = WorkflowOptions1.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into BulkOptions2
        try:
            instance.actual_instance = BulkOptions2.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into ManualOptions2
        try:
            instance.actual_instance = ManualOptions2.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into GiftCardSourceInfo1 with oneOf schemas: BulkOptions2, CampaignOptions2, ManualOptions2, MigrationOptions2, OrderOptions1, StoreCreditOptions1, WorkflowOptions1. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into GiftCardSourceInfo1 with oneOf schemas: BulkOptions2, CampaignOptions2, ManualOptions2, MigrationOptions2, OrderOptions1, StoreCreditOptions1, WorkflowOptions1. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], BulkOptions2, CampaignOptions2, ManualOptions2, MigrationOptions2, OrderOptions1, StoreCreditOptions1, WorkflowOptions1]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


