# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class Service(BaseModel):
    """
    
    """ # noqa: E501
    service_mapping: Optional[Dict[str, Any]] = Field(default=None, description="Action's service mapping.", alias="serviceMapping")
    input_mapping: Optional[StrictStr] = Field(default=None, description="Action's input mapping. Jsonata description of the input this service gets.", alias="inputMapping")
    output_mapping: Optional[StrictStr] = Field(default=None, description="Action's output mapping. Jsonata description of the output this service returns.", alias="outputMapping")
    post_actions: Optional[List[Dict[str, Any]]] = Field(default=None, description="Action's post actions.", alias="postActions")
    post_actions_ids: Optional[Annotated[List[StrictStr], Field(max_length=20)]] = Field(default=None, description="Action's post actions ids.", alias="postActionsIds")
    namespace: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=100)]] = Field(default=None, description="The namespace of the action")
    __properties: ClassVar[List[str]] = ["serviceMapping", "inputMapping", "outputMapping", "postActions", "postActionsIds", "namespace"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Service from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Service from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "serviceMapping": obj.get("serviceMapping"),
            "inputMapping": obj.get("inputMapping"),
            "outputMapping": obj.get("outputMapping"),
            "postActions": obj.get("postActions"),
            "postActionsIds": obj.get("postActionsIds"),
            "namespace": obj.get("namespace")
        })
        return _obj


