# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SortOrder(str, Enum):
    """
    
    """

    """
    allowed enum values
    """
    LEFT_CURLY_BRACKET_BACK_SLASH_DOUBLE_QUOTE_ORDER_BACK_SLASH_DOUBLE_QUOTE_COLON_0_COMMA_BACK_SLASH_DOUBLE_QUOTE_VALUE_BACK_SLASH_DOUBLE_QUOTE_COLON_BACK_SLASH_DOUBLE_QUOTE_ASC_BACK_SLASH_DOUBLE_QUOTE_COMMA_BACK_SLASH_DOUBLE_QUOTE_DESCRIPTION_BACK_SLASH_DOUBLE_QUOTE_COLON_BACK_SLASH_DOUBLE_QUOTE_BACK_SLASH_DOUBLE_QUOTE_COMMA_BACK_SLASH_DOUBLE_QUOTE_MATURITY_BACK_SLASH_DOUBLE_QUOTE_COLON_BACK_SLASH_DOUBLE_QUOTE_GA_BACK_SLASH_DOUBLE_QUOTE_COMMA_BACK_SLASH_DOUBLE_QUOTE_EXPOSURE_BACK_SLASH_DOUBLE_QUOTE_COLON_BACK_SLASH_DOUBLE_QUOTE_PUBLIC_BACK_SLASH_DOUBLE_QUOTE_RIGHT_CURLY_BRACKET = '{\"order\":0,\"value\":\"ASC\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}'
    LEFT_CURLY_BRACKET_BACK_SLASH_DOUBLE_QUOTE_ORDER_BACK_SLASH_DOUBLE_QUOTE_COLON_1_COMMA_BACK_SLASH_DOUBLE_QUOTE_VALUE_BACK_SLASH_DOUBLE_QUOTE_COLON_BACK_SLASH_DOUBLE_QUOTE_DESC_BACK_SLASH_DOUBLE_QUOTE_COMMA_BACK_SLASH_DOUBLE_QUOTE_DESCRIPTION_BACK_SLASH_DOUBLE_QUOTE_COLON_BACK_SLASH_DOUBLE_QUOTE_BACK_SLASH_DOUBLE_QUOTE_COMMA_BACK_SLASH_DOUBLE_QUOTE_MATURITY_BACK_SLASH_DOUBLE_QUOTE_COLON_BACK_SLASH_DOUBLE_QUOTE_GA_BACK_SLASH_DOUBLE_QUOTE_COMMA_BACK_SLASH_DOUBLE_QUOTE_EXPOSURE_BACK_SLASH_DOUBLE_QUOTE_COLON_BACK_SLASH_DOUBLE_QUOTE_PUBLIC_BACK_SLASH_DOUBLE_QUOTE_RIGHT_CURLY_BRACKET = '{\"order\":1,\"value\":\"DESC\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SortOrder from a JSON string"""
        return cls(json.loads(json_str))


