# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class StoreCreditIssuerType(str, Enum):
    """
    
    """

    """
    allowed enum values
    """
    WORKFLOW = 'WORKFLOW'
    BULK = 'BULK'
    MANUAL = 'MANUAL'
    OTHER = 'OTHER'
    REFUND = 'REFUND'
    REFERRAL_REFERRED_CUSTOMER = 'REFERRAL_REFERRED_CUSTOMER'
    REFERRAL_REFERRER = 'REFERRAL_REFERRER'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of StoreCreditIssuerType from a JSON string"""
        return cls(json.loads(json_str))


