# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class StoreCreditContext1(BaseModel):
    """
    Detailed information about the context of a store credit, such as the issuer type and sales channel.
    """ # noqa: E501
    issuer: Optional[StrictStr] = Field(default=None, description="The issuer type of the store credit (e.g., workflow, bulk, manual)")
    issuer_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=50)]] = Field(default=None, description="Indicates a specific instance of the issuer (relevant for workflow/bulk)", alias="issuerId")
    note: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=550)]] = Field(default=None, description="An internal note associated with the store credit")
    source_channel_id: Optional[StrictStr] = Field(default=None, description="The Channel ID of the sales channel that is associated with the store credit (e.g. Shopify channel id)", alias="sourceChannelId")
    source_tenant_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=50)]] = Field(default=None, description="The Tenant ID of the sales channel that is associated with the store credit (e.g. Shopify shop id)", alias="sourceTenantId")
    __properties: ClassVar[List[str]] = ["issuer", "issuerId", "note", "sourceChannelId", "sourceTenantId"]

    @field_validator('issuer')
    def issuer_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['{\"order\":1,\"value\":\"WORKFLOW\",\"description\":\"Issued from a workflow\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', '{\"order\":2,\"value\":\"BULK\",\"description\":\"Issued from a bulk\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', '{\"order\":3,\"value\":\"MANUAL\",\"description\":\"Issued from the Rise dashboard\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', '{\"order\":4,\"value\":\"OTHER\",\"description\":\"Issued from another source\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', '{\"order\":5,\"value\":\"REFUND\",\"description\":\"Issued from a refund\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', '{\"order\":6,\"value\":\"REFERRAL_REFERRED_CUSTOMER\",\"description\":\"Issued from a referral - a referred customer created a wallet from the referral link\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', '{\"order\":7,\"value\":\"REFERRAL_REFERRER\",\"description\":\"Issued from a referral - a referrer made a successful referral. The referred customer placed the first order\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}']):
            raise ValueError("must be one of enum values ('{\"order\":1,\"value\":\"WORKFLOW\",\"description\":\"Issued from a workflow\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', '{\"order\":2,\"value\":\"BULK\",\"description\":\"Issued from a bulk\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', '{\"order\":3,\"value\":\"MANUAL\",\"description\":\"Issued from the Rise dashboard\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', '{\"order\":4,\"value\":\"OTHER\",\"description\":\"Issued from another source\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', '{\"order\":5,\"value\":\"REFUND\",\"description\":\"Issued from a refund\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', '{\"order\":6,\"value\":\"REFERRAL_REFERRED_CUSTOMER\",\"description\":\"Issued from a referral - a referred customer created a wallet from the referral link\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', '{\"order\":7,\"value\":\"REFERRAL_REFERRER\",\"description\":\"Issued from a referral - a referrer made a successful referral. The referred customer placed the first order\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StoreCreditContext1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StoreCreditContext1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "issuer": obj.get("issuer"),
            "issuerId": obj.get("issuerId"),
            "note": obj.get("note"),
            "sourceChannelId": obj.get("sourceChannelId"),
            "sourceTenantId": obj.get("sourceTenantId")
        })
        return _obj


