# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class TokenInfoResponse(BaseModel):
    """
    
    """ # noqa: E501
    active: Optional[StrictBool] = Field(default=None, description="Whether the token is active.")
    subject_type: Optional[StrictStr] = Field(default=None, description="Type of subject to which the token is issued.")
    subject_id: Optional[StrictStr] = Field(default=None, description="ID of the subject to which the token is issued.")
    exp: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Token expiration timestamp.")
    iat: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Token issue timestamp.")
    client_id: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="ID of the app that [created](https://dev.wix.com/docs/rest/app-management/oauth-2/create-access-token) the token, as defined in the [Wix Dev Center](https://dev.wix.com).")
    account_id: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="ID of the account that [created](https://dev.wix.com/docs/rest/app-management/oauth-2/create-access-token) the token, as defined in the [Wix Dev Center](https://dev.wix.com/apps/my-apps).")
    site_id: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="ID of the site to which the token is issued.")
    instance_id: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The [instance ID](https://dev.wix.com/docs/rest/app-management/app-instance/introduction) of the app that the access token was created for. Subscribe to the [Instance App Installed](https://dev.wix.com/docs/rest/app-management/app-instance/app-instance-installed) webhook to receive a notification including the new app instance ID whenever a version of your app is installed on a Wix site.")
    __properties: ClassVar[List[str]] = ["active", "subject_type", "subject_id", "exp", "iat", "client_id", "account_id", "site_id", "instance_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TokenInfoResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TokenInfoResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "active": obj.get("active"),
            "subject_type": obj.get("subject_type"),
            "subject_id": obj.get("subject_id"),
            "exp": obj.get("exp"),
            "iat": obj.get("iat"),
            "client_id": obj.get("client_id"),
            "account_id": obj.get("account_id"),
            "site_id": obj.get("site_id"),
            "instance_id": obj.get("instance_id")
        })
        return _obj


