# coding: utf-8

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.action_initiator2 import ActionInitiator2
from openapi_client.models.external_event2 import ExternalEvent2
from openapi_client.models.notifications1 import Notifications1
from openapi_client.models.store_credit_context2 import StoreCreditContext2
from openapi_client.models.wallet_action_execution_details1 import WalletActionExecutionDetails1
from openapi_client.models.wallet_action_execution_details2 import WalletActionExecutionDetails2
from typing import Optional, Set
from typing_extensions import Self

class WalletAction2(BaseModel):
    """
    The updated WalletAction.
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="WalletAction ID.")
    revision: Optional[StrictStr] = Field(default=None, description="Represents the current state of an item. Each time the item is modified, its `revision` changes. For an update operation to succeed, you MUST pass the latest revision.")
    created_date: Optional[datetime] = Field(default=None, description="Represents the time this WalletAction was created.", alias="createdDate")
    updated_date: Optional[datetime] = Field(default=None, description="Represents the time this WalletAction was last updated.", alias="updatedDate")
    start_date: Optional[datetime] = Field(default=None, description="Represents the time at which the WalletAction's amount will be added to the account. Defaults to immediately.", alias="startDate")
    expiration_date: Optional[datetime] = Field(default=None, description="Represents the time at which the unused balance of the WalletAction will be deducted from the account. Defaults to never.", alias="expirationDate")
    disable_date: Optional[datetime] = Field(default=None, description="Represents the time at which the WalletAction was manually disabled, if applicable.", alias="disableDate")
    amount: Optional[StrictStr] = Field(default=None, description="The amount to be added to the Wallet.")
    note: Optional[Annotated[str, Field(strict=True, max_length=550)]] = Field(default=None, description="Free text comment regarding the WalletAction context (**Deprecated**: Use `note` instead.)")
    type: Optional[StrictStr] = Field(default=None, description="Indicates the kind of the specific WalletAction (**Deprecated**)")
    wallet_action_started: Optional[WalletActionExecutionDetails1] = Field(default=None, alias="walletActionStarted")
    wallet_action_ended: Optional[WalletActionExecutionDetails2] = Field(default=None, alias="walletActionEnded")
    status: Optional[StrictStr] = Field(default=None, description="The current status of the WalletAction. Set to PENDING when the WalletAction is created and updated to ACTIVE when the amount is added to the wallet.")
    source: Optional[ActionInitiator2] = None
    notifications: Optional[Notifications1] = None
    liability: Optional[StrictBool] = Field(default=None, description="Indicates whether the WalletAction is a liability. The default is false.")
    store_credit_context: Optional[StoreCreditContext2] = Field(default=None, alias="storeCreditContext")
    external_event: Optional[ExternalEvent2] = Field(default=None, alias="externalEvent")
    wallet_id: Optional[StrictStr] = Field(default=None, description="ID of the wallet to which the WalletAction belongs.", alias="walletId")
    idempotency_key: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=100)]] = Field(default=None, description="Unique key to identify the WalletAction, used to prevent duplicate WalletActions from being created in case of retries or network issues. The key should be unique for each WalletAction and should not be reused.", alias="idempotencyKey")
    __properties: ClassVar[List[str]] = ["id", "revision", "createdDate", "updatedDate", "startDate", "expirationDate", "disableDate", "amount", "note", "type", "walletActionStarted", "walletActionEnded", "status", "source", "notifications", "liability", "storeCreditContext", "externalEvent", "walletId", "idempotencyKey"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['{\"order\":0,\"value\":\"UNKNOWN\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', '{\"order\":1,\"value\":\"REWARD\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', '{\"order\":2,\"value\":\"REFUND\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}']):
            raise ValueError("must be one of enum values ('{\"order\":0,\"value\":\"UNKNOWN\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', '{\"order\":1,\"value\":\"REWARD\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', '{\"order\":2,\"value\":\"REFUND\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['{\"order\":0,\"value\":\"PENDING\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', '{\"order\":1,\"value\":\"ACTIVE\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', '{\"order\":2,\"value\":\"DISABLED\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', '{\"order\":3,\"value\":\"EXPIRED\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', '{\"order\":4,\"value\":\"FAILED\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}']):
            raise ValueError("must be one of enum values ('{\"order\":0,\"value\":\"PENDING\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', '{\"order\":1,\"value\":\"ACTIVE\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', '{\"order\":2,\"value\":\"DISABLED\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', '{\"order\":3,\"value\":\"EXPIRED\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}', '{\"order\":4,\"value\":\"FAILED\",\"description\":\"\",\"maturity\":\"GA\",\"exposure\":\"PUBLIC\"}')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WalletAction2 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "revision",
            "created_date",
            "updated_date",
            "disable_date",
            "status",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of wallet_action_started
        if self.wallet_action_started:
            _dict['walletActionStarted'] = self.wallet_action_started.to_dict()
        # override the default output from pydantic by calling `to_dict()` of wallet_action_ended
        if self.wallet_action_ended:
            _dict['walletActionEnded'] = self.wallet_action_ended.to_dict()
        # override the default output from pydantic by calling `to_dict()` of source
        if self.source:
            _dict['source'] = self.source.to_dict()
        # override the default output from pydantic by calling `to_dict()` of notifications
        if self.notifications:
            _dict['notifications'] = self.notifications.to_dict()
        # override the default output from pydantic by calling `to_dict()` of store_credit_context
        if self.store_credit_context:
            _dict['storeCreditContext'] = self.store_credit_context.to_dict()
        # override the default output from pydantic by calling `to_dict()` of external_event
        if self.external_event:
            _dict['externalEvent'] = self.external_event.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WalletAction2 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "revision": obj.get("revision"),
            "createdDate": obj.get("createdDate"),
            "updatedDate": obj.get("updatedDate"),
            "startDate": obj.get("startDate"),
            "expirationDate": obj.get("expirationDate"),
            "disableDate": obj.get("disableDate"),
            "amount": obj.get("amount"),
            "note": obj.get("note"),
            "type": obj.get("type"),
            "walletActionStarted": WalletActionExecutionDetails1.from_dict(obj["walletActionStarted"]) if obj.get("walletActionStarted") is not None else None,
            "walletActionEnded": WalletActionExecutionDetails2.from_dict(obj["walletActionEnded"]) if obj.get("walletActionEnded") is not None else None,
            "status": obj.get("status"),
            "source": ActionInitiator2.from_dict(obj["source"]) if obj.get("source") is not None else None,
            "notifications": Notifications1.from_dict(obj["notifications"]) if obj.get("notifications") is not None else None,
            "liability": obj.get("liability"),
            "storeCreditContext": StoreCreditContext2.from_dict(obj["storeCreditContext"]) if obj.get("storeCreditContext") is not None else None,
            "externalEvent": ExternalEvent2.from_dict(obj["externalEvent"]) if obj.get("externalEvent") is not None else None,
            "walletId": obj.get("walletId"),
            "idempotencyKey": obj.get("idempotencyKey")
        })
        return _obj


