# coding: utf-8

# flake8: noqa

"""
    Rise.ai API Documentation

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "GiftCardApi",
    "GiftCardOrderApi",
    "OAuthApi",
    "RecipientApi",
    "TransactionApi",
    "WalletApi",
    "WalletActionApi",
    "WorkflowsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AccessTokenRequest",
    "Action",
    "ActionAttributes",
    "ActionCompletedRequest",
    "ActionData",
    "ActionEvent",
    "ActionInitiator",
    "ActionInitiator1",
    "ActionInitiator2",
    "ActionInitiator3",
    "ActionRetryRequest",
    "ActionSettings",
    "Actions",
    "Actions1",
    "ActionsData",
    "Activation",
    "ActivationContext",
    "ActivationContinuedAfterSchedule",
    "ActivationRequest",
    "ActivationResumeAfterDelay",
    "ActivationScheduleCompleted",
    "ActivationScheduleRequested",
    "AddCustomerReferenceRequest",
    "AddCustomerReferenceResponse",
    "AggregationData",
    "AggregationData1",
    "AggregationResults1",
    "AggregationType",
    "AppDefinedAction",
    "AppDefinedActionInfo",
    "ApplicationError",
    "ApplicationOrigin",
    "AutomationConfiguration",
    "AutomationSettings",
    "BatchActivationRequest",
    "BillingInfo",
    "BillingInfo1",
    "BlockType",
    "Body",
    "BoolValue",
    "BulkActionMetadata",
    "BulkCancelEventRequest",
    "BulkCancelEventResponse",
    "BulkCancelEventResult",
    "BulkDeleteGiftCardsByFilterRequest",
    "BulkDeleteGiftCardsByFilterResponse",
    "BulkOptions",
    "BulkOptions1",
    "BulkOptions2",
    "BulkReportEventRequest",
    "BulkReportEventResponse",
    "BulkReportEventResult",
    "BulkUpdateWalletActionTagsByFilterRequest",
    "BulkUpdateWalletActionTagsByFilterResponse",
    "BulkUpdateWalletActionTagsRequest",
    "BulkUpdateWalletActionTagsResponse",
    "BulkUpdateWalletActionTagsResult",
    "BuyerInfo",
    "BuyerInfo1",
    "By",
    "CampaignOptions",
    "CampaignOptions1",
    "CampaignOptions2",
    "CancelEventRequest",
    "CancellationReason",
    "CancelledStatusInfo",
    "Case",
    "ConditionAction",
    "ConditionActionInfo",
    "ConditionBlock",
    "ConditionExpressionGroup",
    "ConditionFilter",
    "ConsumeReportEventRequest",
    "ContactDetails",
    "ContactDetails1",
    "CountGiftCardsRequest",
    "CountGiftCardsResponse",
    "CountGiftCardsResponse1",
    "CountWalletsRequest",
    "CountWalletsResponse",
    "CountWalletsResponse1",
    "CreateAccessTokenResponse",
    "CreateCustomerReferenceRequest",
    "CreateCustomerReferenceResponse",
    "CreateGiftCard428Response",
    "CreateGiftCardRequest",
    "CreateGiftCardResponse",
    "CreateGiftCardResponse1",
    "CreateMigrationGiftCardRequest",
    "CreateMigrationGiftCardResponse",
    "CreateMigrationRecipientRequest",
    "CreateMigrationRecipientResponse",
    "CreateMigrationTransactionRequest",
    "CreateMigrationTransactionResponse",
    "CreateMigrationWalletActionRequest",
    "CreateMigrationWalletActionResponse",
    "CreateOrderRequest",
    "CreateOrderResponse",
    "CreateOrderResponse1",
    "CreateRecipientRequest",
    "CreateRecipientResponse",
    "CreateRecipientResponse1",
    "CreateWalletAction400Response",
    "CreateWalletActionByCustomerReferenceRequest",
    "CreateWalletActionByCustomerReferenceResponse",
    "CreateWalletActionByCustomerReferenceResponse1",
    "CreateWalletActionRequest",
    "CreateWalletActionResponse",
    "CreateWalletActionResponse1",
    "CreateWalletRequest",
    "CreateWalletResponse",
    "CreateWalletResponse1",
    "CreateWalletV2Request",
    "CreateWalletV2Response",
    "CursorPaging",
    "CursorPaging1",
    "CursorPaging2",
    "CursorPaging3",
    "CursorPaging4",
    "CursorPagingMetadata",
    "CursorPagingMetadata1",
    "CursorPagingMetadata2",
    "CursorPagingMetadata3",
    "Cursors",
    "Cursors1",
    "Cursors2",
    "Cursors3",
    "Cursors4",
    "Cursors5",
    "CustomerReference",
    "CustomerReference1",
    "CustomerReference2",
    "CustomerReference3",
    "CustomerReference4",
    "CustomerReference5",
    "CustomerReferenceQuery",
    "DISABLEDATDATESET",
    "DISABLEDATDATESETDetails",
    "DISABLEDATDATESETDetailsApplicationError",
    "DateHistogramAggregation",
    "DateHistogramResult",
    "DateHistogramResult1",
    "DateHistogramResults",
    "DateHistogramResults1",
    "DecreaseBalance428Response",
    "DecreaseBalanceRequest",
    "DecreaseBalanceResponse",
    "DecreaseBalanceResponse1",
    "DelayAction",
    "DelayActionInfo",
    "DelayHelper",
    "DeleteCustomerReferenceRequest",
    "DeleteOrderRequest",
    "DeleteRecipientRequest",
    "DeleteWalletActionRequest",
    "DisableGiftCardRequest",
    "DisableGiftCardResponse",
    "DisableGiftCardResponse1",
    "DisableWalletAction428Response",
    "DisableWalletActionRequest",
    "DisableWalletActionResponse",
    "DisableWalletActionResponse1",
    "Domain",
    "DoubleValue",
    "DraftInfo",
    "EXISTINGIDEMPOTENCYKEY",
    "EXISTINGIDEMPOTENCYKEYDetails",
    "EXISTINGIDEMPOTENCYKEYDetailsApplicationError",
    "EXPIRATIONDATEINTHEPAST",
    "EXPIRATIONDATEINTHEPASTDetails",
    "EXPIRATIONDATEINTHEPASTDetailsApplicationError",
    "EmailParams",
    "EmailParams1",
    "EndMigrationWalletActionRequest",
    "EndMigrationWalletActionResponse",
    "Enrichment",
    "Enrichments",
    "EntityCreatedEvent",
    "EntityDeletedEvent",
    "EntityUpdatedEvent",
    "ErrorReason",
    "EventInfo",
    "ExecuteFromActionRequest",
    "Expiration1",
    "ExpirationType",
    "ExpressionEvaluationResult",
    "ExpressionResults",
    "ExtendedFields",
    "ExternalEvent",
    "ExternalEvent1",
    "ExternalEvent2",
    "ExternalEventType",
    "FailedStatusInfo",
    "FailureInfo",
    "FieldMask",
    "Fields",
    "Fields1",
    "Fields2",
    "Filter",
    "Filter1",
    "Filter2",
    "Filter3",
    "Filter4",
    "FilterValueSelection",
    "FilterableAppDefinedActions",
    "FixedDate",
    "FraudType",
    "FulfillOrderRequest",
    "FulfilledData",
    "FulfilledData1",
    "FulfillmentStatus",
    "FutureDateActivationOffset",
    "GIFTCARDDISABLED",
    "GIFTCARDDISABLEDDetails",
    "GIFTCARDDISABLEDDetailsApplicationError",
    "GIFTCARDEXPIRED",
    "GIFTCARDEXPIREDDetails",
    "GIFTCARDEXPIREDDetailsApplicationError",
    "GIFTCARDNOTFOUND",
    "GIFTCARDNOTFOUNDDetails",
    "GIFTCARDNOTFOUNDDetailsApplicationError",
    "GetCustomerReferenceRequest",
    "GetCustomerReferenceResponse",
    "GetCustomerReferenceResponse1",
    "GetGiftCard428Response",
    "GetGiftCardConsistentRequest",
    "GetGiftCardConsistentResponse",
    "GetGiftCardRequest",
    "GetGiftCardResponse",
    "GetGiftCardResponse1",
    "GetOrCreateWalletRequest",
    "GetOrCreateWalletResponse",
    "GetOrCreateWalletResponse1",
    "GetOrCreateWalletV2Request",
    "GetOrCreateWalletV2Response",
    "GetOrderRequest",
    "GetOrderResponse",
    "GetRecipientRequest",
    "GetRecipientResponse",
    "GetRecipientResponse1",
    "GetRefundableAmountsRequest",
    "GetRefundableAmountsResponse",
    "GetRefundableAmountsResponse1",
    "GetWalletActionRequest",
    "GetWalletActionResponse",
    "GetWalletGiftCardRequest",
    "GetWalletGiftCardResponse",
    "GetWalletRequest",
    "GetWalletResponse",
    "GetWalletResponse1",
    "GetWalletV2Request",
    "GetWalletV2Response",
    "GiftCard",
    "GiftCard1",
    "GiftCard2",
    "GiftCard3",
    "GiftCard4",
    "GiftCard5",
    "GiftCard6",
    "GiftCard7",
    "GiftCardCodeRegenerated",
    "GiftCardDisabled",
    "GiftCardDisabledDetails",
    "GiftCardExpired",
    "GiftCardExpiredDetails",
    "GiftCardGiftCardServiceV1RiseGiftCardsCountPostCountGiftCardsRequestBody",
    "GiftCardGiftCardServiceV1RiseGiftCardsGiftCardIdPatchUpdateGiftCardRequestBody",
    "GiftCardGiftCardServiceV1RiseGiftCardsPostCreateGiftCardRequestBody",
    "GiftCardGiftCardServiceV1RiseGiftCardsQueryPostQueryGiftCardsRequestBody",
    "GiftCardGiftCardServiceV1RiseGiftCardsSearchPostSearchGiftCardsRequestBody",
    "GiftCardGiftCardServiceV1RiseGiftCardsTransactionGiftCardIdDecreasePostDecreaseBalanceRequestBody",
    "GiftCardGiftCardServiceV1RiseGiftCardsTransactionGiftCardIdIncreasePostIncreaseBalanceRequestBody",
    "GiftCardIdempotencyKeyDetails",
    "GiftCardInfo",
    "GiftCardInfo1",
    "GiftCardInitialized",
    "GiftCardLineItem",
    "GiftCardLineItem1",
    "GiftCardNotFoundDetails",
    "GiftCardOptions",
    "GiftCardOrder",
    "GiftCardOrder1",
    "GiftCardOrder2",
    "GiftCardOrder3",
    "GiftCardOrder4",
    "GiftCardOrder5",
    "GiftCardOrderGiftCardOrderServiceV1RiseOrdersFulfillPostFulfillOrderRequestBody",
    "GiftCardOrderGiftCardOrderServiceV1RiseOrdersOrderIdPatchUpdateOrderRequestBody",
    "GiftCardOrderGiftCardOrderServiceV1RiseOrdersPostCreateOrderRequestBody",
    "GiftCardOrderGiftCardOrderServiceV1RiseOrdersQueryPostQueryOrdersRequestBody",
    "GiftCardOrderGiftCardOrderServiceV1RiseOrdersStatusPostUpdateOrderStatusRequestBody",
    "GiftCardSourceInfo1",
    "GiftCardSourceInfo2",
    "GiftCardTransactionInsufficientFunds",
    "GiftCardType",
    "GiftingDetails",
    "GiftingDetails1",
    "GiftingInfo",
    "GiftingInfo1",
    "GroupByValueResults",
    "GroupByValueResults1",
    "GroupedByValue",
    "Helper",
    "INSUFFICIENTFUNDS",
    "INSUFFICIENTFUNDSDetails",
    "INSUFFICIENTFUNDSDetailsApplicationError",
    "INVALIDCODE",
    "INVALIDCODEDetails",
    "INVALIDCODEDetailsApplicationError",
    "INVALIDEXPIRATIONDATE",
    "INVALIDEXPIRATIONDATEDetails",
    "INVALIDEXPIRATIONDATEDetailsApplicationError",
    "INVALIDGIFTCARDBALANCE",
    "INVALIDGIFTCARDBALANCEDetails",
    "INVALIDGIFTCARDBALANCEDetailsApplicationError",
    "Id",
    "Id1",
    "Idempotency",
    "Idempotency1",
    "IdempotencyKeyDetails",
    "Identifier",
    "IdentifierType",
    "Identity",
    "IfFilter",
    "IncludeMissingValuesOptions",
    "IncludeMissingValuesOptions1",
    "IncreaseBalance428Response",
    "IncreaseBalanceRequest",
    "IncreaseBalanceResponse",
    "IncreaseBalanceResponse1",
    "Info",
    "InitialOptions",
    "InitialOptions1",
    "InitiatedStatusInfo",
    "InitiatorType",
    "InsufficientFundsDetails",
    "Int32Value",
    "Int64Value",
    "Interval",
    "InvalidCodeDetails",
    "InvalidExpirationDateDetails",
    "InvalidGiftCardBalanceDetails",
    "InvalidWalletActionDetails",
    "ItemMetadata",
    "Kind",
    "Kind1",
    "ListValue",
    "ManualOptions",
    "ManualOptions1",
    "ManualOptions2",
    "MessageEnvelope",
    "MigrateWalletRequest",
    "MigrateWalletResponse",
    "MigrationOptions",
    "MigrationOptions1",
    "MigrationOptions2",
    "MissingValues",
    "Mode",
    "Namespaces",
    "Nested",
    "NestedAggregation",
    "NestedAggregationResults1",
    "NestedAggregationType",
    "NestedResultValue1",
    "NestedResults",
    "NestedResults1",
    "NestedValueAggregationResult",
    "NestedValueAggregationResult1",
    "Notifications",
    "Notifications1",
    "NullValue",
    "NumberValue",
    "OAuthOauth2TokenPostSomeOperationRequestBody",
    "Of",
    "OperationType",
    "Operator",
    "Options",
    "Options1",
    "OrderOptions",
    "OrderOptions1",
    "OrderQuery1",
    "OrderQuery2",
    "OrderSourceInfo",
    "OrderSourceInfo1",
    "OrderStatus",
    "Origin",
    "OriginInfo",
    "Output",
    "OutputAction",
    "Paging",
    "Paging1",
    "Paging2",
    "PagingMetadataV2",
    "PagingMetadataV21",
    "PagingMetadataV22",
    "PagingMetadataV23",
    "PagingMetadataV24",
    "PagingMethod",
    "PagingMethod1",
    "PagingMethod2",
    "PagingMethod3",
    "Path",
    "PaymentMethodRefundOptions",
    "PaymentMethodRefundOptions1",
    "PaymentMethodRefundWalletActionDetails",
    "PaymentMethodRefundWalletActionDetails1",
    "PaymentStatus",
    "PreinstalledIdentifier",
    "PreinstalledOrigin",
    "ProduceTransactionAddedEventRequest",
    "QueryByContact",
    "QueryByContact1",
    "QueryGiftCardsRequest",
    "QueryGiftCardsResponse",
    "QueryGiftCardsResponse1",
    "QueryOrdersRequest",
    "QueryOrdersResponse",
    "QueryOrdersResponse1",
    "QueryRecipientsRequest",
    "QueryRecipientsResponse",
    "QueryRecipientsResponse1",
    "QueryTransactionsInternalRequest",
    "QueryTransactionsInternalResponse",
    "QueryTransactionsRequest",
    "QueryTransactionsResponse",
    "QueryTransactionsResponse1",
    "QueryUnredeemedWalletActionsRequest",
    "QueryUnredeemedWalletActionsResponse",
    "QueryUnredeemedWalletActionsResponse1",
    "QueryV21",
    "QueryV22",
    "QueryWalletActionBalancesRequest",
    "QueryWalletActionBalancesResponse",
    "QueryWalletActionBalancesResponse1",
    "QueryWalletActionRequest",
    "QueryWalletActionResponse",
    "QueryWalletActionResponse1",
    "QueryWalletsByContactRequest",
    "QueryWalletsByContactResponse",
    "QueryWalletsByContactResponse1",
    "QueryWalletsRequest",
    "QueryWalletsResponse",
    "QueryWalletsResponse1",
    "REQUIREDPROPERTY",
    "REQUIREDPROPERTYDetails",
    "REQUIREDPROPERTYDetailsApplicationError",
    "RangeAggregation",
    "RangeAggregationResult",
    "RangeAggregationResult1",
    "RangeBucket",
    "RangeResult",
    "RangeResults",
    "RangeResults1",
    "RateLimit",
    "RateLimitAction",
    "RateLimitActionInfo",
    "RateLimiting",
    "Recipient",
    "Recipient1",
    "Recipient2",
    "Recipient3",
    "Recipient4",
    "RecipientGiftCardRecipientServiceV1RiseRecipientsPostCreateRecipientRequestBody",
    "RecipientGiftCardRecipientServiceV1RiseRecipientsQueryPostQueryRecipientsRequestBody",
    "RedeemOptions",
    "RedeemOptions1",
    "RefreshPayloadRequest",
    "RefreshPayloadResponse",
    "RefreshTokenResponse",
    "RefundTransactionContext",
    "RefundTransactionRequest",
    "RefundableAmount",
    "RefundableAmount1",
    "RegenerateCodeRequest",
    "RegenerateCodeResponse",
    "RelativeExpiresAt",
    "RelativeExpiresAt1",
    "ReportDomainEventRequest",
    "ReportEventRequest",
    "ReportEventResponse",
    "ReportEventResponse1",
    "RequestedFields",
    "RestoreInfo",
    "Result",
    "Results",
    "Results1",
    "RewardOptions",
    "RewardOptions1",
    "RunAutomationRequest",
    "RunAutomationResponse",
    "SCHEMAVALIDATIONFAILED",
    "SCHEMAVALIDATIONFAILEDDetails",
    "SCHEMAVALIDATIONFAILEDDetailsApplicationError",
    "STARTDATEINTHEPAST",
    "STARTDATEINTHEPASTDetails",
    "STARTDATEINTHEPASTDetailsApplicationError",
    "STARTLATERTHANEXPIRATION",
    "STARTLATERTHANEXPIRATIONDetails",
    "STARTLATERTHANEXPIRATIONDetailsApplicationError",
    "ScalarAggregation",
    "ScalarResult",
    "ScalarResult1",
    "ScalarType",
    "Schedule",
    "ScheduleActivationRequested",
    "ScheduleRequest",
    "ScheduleResponse",
    "ScheduleStatus",
    "ScheduledAction",
    "ScheduledStatusInfo",
    "Scheduler",
    "SearchDetails",
    "SearchGiftCardsRequest",
    "SearchGiftCardsResponse",
    "SearchGiftCardsResponse1",
    "Service",
    "ServiceMapping",
    "SetVariables",
    "SetVariablesAction",
    "SetVariablesActionInfo",
    "SideEffects",
    "SideEffects1",
    "SideEffects2",
    "SimpleDelay",
    "SkipReason",
    "SkippedStatusInfo",
    "SortDirection",
    "SortOrder",
    "SortType",
    "Sorting",
    "Sorting1",
    "Sorting2",
    "Source",
    "SpiAction",
    "SplitAction",
    "Status",
    "StatusInfo",
    "StoreCreditContext",
    "StoreCreditContext1",
    "StoreCreditContext2",
    "StoreCreditIssuerType",
    "StoreCreditOptions",
    "StoreCreditOptions1",
    "StoreCreditRefundOptions",
    "StoreCreditRefundOptions1",
    "StringValue",
    "Struct",
    "StructValue",
    "SubjectType",
    "SuccessInfo",
    "SwitchFilter",
    "TagList",
    "Tags",
    "TagsModified",
    "Target",
    "TimePeriod",
    "TimeUnit",
    "Timestamp",
    "TokenInfoResponse",
    "Transaction1",
    "Transaction2",
    "Transaction3",
    "TransactionAdded",
    "TransactionDetails",
    "TransactionDetails1",
    "TransactionOptions",
    "TransactionSourceInfo",
    "TransactionSourceInfo1",
    "TransactionTransactionQueryServiceV1RiseGiftCardsTransactionsQueryPostQueryTransactionsRequestBody",
    "TransactionType",
    "TransactionWrapper",
    "TransactionWrapper1",
    "TransactionWrapper2",
    "TransactionWrapper3",
    "Trigger",
    "TriggerInfo",
    "Type",
    "TypeInfo",
    "Units",
    "UpdateCustomerReferenceRequest",
    "UpdateCustomerReferenceResponse",
    "UpdateGiftCardRequest",
    "UpdateGiftCardResponse",
    "UpdateGiftCardResponse1",
    "UpdateLastActivityForRemindersRequest",
    "UpdateLastActivityForRemindersResponse",
    "UpdateOrderRequest",
    "UpdateOrderResponse",
    "UpdateOrderResponse1",
    "UpdateOrderStatusRequest",
    "UpdatePendingSchedulesPayloadRequest",
    "UpdateWalletAction400Response",
    "UpdateWalletAction428Response",
    "UpdateWalletActionRequest",
    "UpdateWalletActionResponse",
    "UpdateWalletActionResponse1",
    "Value1",
    "ValueAggregationResult",
    "ValueAggregationResult1",
    "ValueResult",
    "ValueResults",
    "ValueResults1",
    "VoidFailedDetails",
    "VoidOptions",
    "VoidOptions1",
    "VoidTransactionRequest",
    "VoidTransactionResponse",
    "WALLETACTIONALREADYACTIVE",
    "WALLETACTIONALREADYACTIVEDetails",
    "WALLETACTIONALREADYACTIVEDetailsApplicationError",
    "WALLETACTIONALREADYEXPIRED",
    "WALLETACTIONALREADYEXPIREDDetails",
    "WALLETACTIONALREADYEXPIREDDetailsApplicationError",
    "WALLETACTIONEXCEEDSMAXIMUMBALANCE",
    "WALLETACTIONEXCEEDSMAXIMUMBALANCEDetails",
    "WALLETACTIONEXCEEDSMAXIMUMBALANCEDetailsApplicationError",
    "WALLETACTIONNOTACTIVE",
    "WALLETACTIONNOTACTIVEDetails",
    "WALLETACTIONNOTACTIVEDetailsApplicationError",
    "Wallet",
    "Wallet1",
    "Wallet2",
    "Wallet3",
    "Wallet4",
    "Wallet5",
    "WalletAction",
    "WalletAction1",
    "WalletAction2",
    "WalletAction3",
    "WalletAction4",
    "WalletAction5",
    "WalletAction6",
    "WalletAction7",
    "WalletAction8",
    "WalletActionCreationDisabledAtDateSetDetails",
    "WalletActionCreationExpirationDateInThePastDetails",
    "WalletActionCreationStartLaterThanExpirationDetails",
    "WalletActionDisabled",
    "WalletActionEndOptions",
    "WalletActionEndOptions1",
    "WalletActionEndReason",
    "WalletActionExceedsMaximumBalanceDetails",
    "WalletActionExecutionDetails",
    "WalletActionExecutionDetails1",
    "WalletActionExecutionDetails2",
    "WalletActionExpired",
    "WalletActionIdempotencyKeyDetails",
    "WalletActionStartOptions",
    "WalletActionStartOptions1",
    "WalletActionStarted",
    "WalletActionStatus",
    "WalletActionType",
    "WalletActionUpdateExpirationDateInThePastDetails",
    "WalletActionUpdateStartDateInThePastDetails",
    "WalletActionUpdateStartLaterThanExpirationDetails",
    "WalletActionWalletActionServiceV1RiseWalletActionsByCustomerReferencePostCreateWalletActionByCustomerReferenceRequestBody",
    "WalletActionWalletActionServiceV1RiseWalletActionsPostCreateWalletActionRequestBody",
    "WalletActionWalletActionServiceV1RiseWalletActionsQueryBalancesPostQueryWalletActionsBalancesRequestBody",
    "WalletActionWalletActionServiceV1RiseWalletActionsQueryPostQueryWalletActionsRequestBody",
    "WalletActionWalletActionServiceV1RiseWalletActionsQueryUnredeemedPostQueryUnredeemedWalletActionsRequestBody",
    "WalletActionWalletActionServiceV1RiseWalletActionsWalletActionIdDisablePostDisableWalletActionRequestBody",
    "WalletActionWalletActionServiceV1RiseWalletActionsWalletActionIdPatchUpdateWalletActionRequestBody",
    "WalletActionWithBalance",
    "WalletActionWithBalance1",
    "WalletWalletServiceV1RiseWalletsCountPostCountWalletsRequestBody",
    "WalletWalletServiceV1RiseWalletsIssuePostGetOrCreateWalletRequestBody",
    "WalletWalletServiceV1RiseWalletsPostCreateWalletRequestBody",
    "WalletWalletServiceV1RiseWalletsQueryByContactPostQueryWalletsByContactRequestBody",
    "WalletWalletServiceV1RiseWalletsQueryPostQueryWalletsRequestBody",
    "WebhookIdentityType",
    "WorkflowOptions",
    "WorkflowOptions1",
    "WorkflowsEsbConfigResolverWorkflowsV1EventsReportPostReportEventRequestBody",
]

# import apis into sdk package
from openapi_client.api.gift_card_api import GiftCardApi as GiftCardApi
from openapi_client.api.gift_card_order_api import GiftCardOrderApi as GiftCardOrderApi
from openapi_client.api.o_auth_api import OAuthApi as OAuthApi
from openapi_client.api.recipient_api import RecipientApi as RecipientApi
from openapi_client.api.transaction_api import TransactionApi as TransactionApi
from openapi_client.api.wallet_api import WalletApi as WalletApi
from openapi_client.api.wallet_action_api import WalletActionApi as WalletActionApi
from openapi_client.api.workflows_api import WorkflowsApi as WorkflowsApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.access_token_request import AccessTokenRequest as AccessTokenRequest
from openapi_client.models.action import Action as Action
from openapi_client.models.action_attributes import ActionAttributes as ActionAttributes
from openapi_client.models.action_completed_request import ActionCompletedRequest as ActionCompletedRequest
from openapi_client.models.action_data import ActionData as ActionData
from openapi_client.models.action_event import ActionEvent as ActionEvent
from openapi_client.models.action_initiator import ActionInitiator as ActionInitiator
from openapi_client.models.action_initiator1 import ActionInitiator1 as ActionInitiator1
from openapi_client.models.action_initiator2 import ActionInitiator2 as ActionInitiator2
from openapi_client.models.action_initiator3 import ActionInitiator3 as ActionInitiator3
from openapi_client.models.action_retry_request import ActionRetryRequest as ActionRetryRequest
from openapi_client.models.action_settings import ActionSettings as ActionSettings
from openapi_client.models.actions import Actions as Actions
from openapi_client.models.actions1 import Actions1 as Actions1
from openapi_client.models.actions_data import ActionsData as ActionsData
from openapi_client.models.activation import Activation as Activation
from openapi_client.models.activation_context import ActivationContext as ActivationContext
from openapi_client.models.activation_continued_after_schedule import ActivationContinuedAfterSchedule as ActivationContinuedAfterSchedule
from openapi_client.models.activation_request import ActivationRequest as ActivationRequest
from openapi_client.models.activation_resume_after_delay import ActivationResumeAfterDelay as ActivationResumeAfterDelay
from openapi_client.models.activation_schedule_completed import ActivationScheduleCompleted as ActivationScheduleCompleted
from openapi_client.models.activation_schedule_requested import ActivationScheduleRequested as ActivationScheduleRequested
from openapi_client.models.add_customer_reference_request import AddCustomerReferenceRequest as AddCustomerReferenceRequest
from openapi_client.models.add_customer_reference_response import AddCustomerReferenceResponse as AddCustomerReferenceResponse
from openapi_client.models.aggregation_data import AggregationData as AggregationData
from openapi_client.models.aggregation_data1 import AggregationData1 as AggregationData1
from openapi_client.models.aggregation_results1 import AggregationResults1 as AggregationResults1
from openapi_client.models.aggregation_type import AggregationType as AggregationType
from openapi_client.models.app_defined_action import AppDefinedAction as AppDefinedAction
from openapi_client.models.app_defined_action_info import AppDefinedActionInfo as AppDefinedActionInfo
from openapi_client.models.application_error import ApplicationError as ApplicationError
from openapi_client.models.application_origin import ApplicationOrigin as ApplicationOrigin
from openapi_client.models.automation_configuration import AutomationConfiguration as AutomationConfiguration
from openapi_client.models.automation_settings import AutomationSettings as AutomationSettings
from openapi_client.models.batch_activation_request import BatchActivationRequest as BatchActivationRequest
from openapi_client.models.billing_info import BillingInfo as BillingInfo
from openapi_client.models.billing_info1 import BillingInfo1 as BillingInfo1
from openapi_client.models.block_type import BlockType as BlockType
from openapi_client.models.body import Body as Body
from openapi_client.models.bool_value import BoolValue as BoolValue
from openapi_client.models.bulk_action_metadata import BulkActionMetadata as BulkActionMetadata
from openapi_client.models.bulk_cancel_event_request import BulkCancelEventRequest as BulkCancelEventRequest
from openapi_client.models.bulk_cancel_event_response import BulkCancelEventResponse as BulkCancelEventResponse
from openapi_client.models.bulk_cancel_event_result import BulkCancelEventResult as BulkCancelEventResult
from openapi_client.models.bulk_delete_gift_cards_by_filter_request import BulkDeleteGiftCardsByFilterRequest as BulkDeleteGiftCardsByFilterRequest
from openapi_client.models.bulk_delete_gift_cards_by_filter_response import BulkDeleteGiftCardsByFilterResponse as BulkDeleteGiftCardsByFilterResponse
from openapi_client.models.bulk_options import BulkOptions as BulkOptions
from openapi_client.models.bulk_options1 import BulkOptions1 as BulkOptions1
from openapi_client.models.bulk_options2 import BulkOptions2 as BulkOptions2
from openapi_client.models.bulk_report_event_request import BulkReportEventRequest as BulkReportEventRequest
from openapi_client.models.bulk_report_event_response import BulkReportEventResponse as BulkReportEventResponse
from openapi_client.models.bulk_report_event_result import BulkReportEventResult as BulkReportEventResult
from openapi_client.models.bulk_update_wallet_action_tags_by_filter_request import BulkUpdateWalletActionTagsByFilterRequest as BulkUpdateWalletActionTagsByFilterRequest
from openapi_client.models.bulk_update_wallet_action_tags_by_filter_response import BulkUpdateWalletActionTagsByFilterResponse as BulkUpdateWalletActionTagsByFilterResponse
from openapi_client.models.bulk_update_wallet_action_tags_request import BulkUpdateWalletActionTagsRequest as BulkUpdateWalletActionTagsRequest
from openapi_client.models.bulk_update_wallet_action_tags_response import BulkUpdateWalletActionTagsResponse as BulkUpdateWalletActionTagsResponse
from openapi_client.models.bulk_update_wallet_action_tags_result import BulkUpdateWalletActionTagsResult as BulkUpdateWalletActionTagsResult
from openapi_client.models.buyer_info import BuyerInfo as BuyerInfo
from openapi_client.models.buyer_info1 import BuyerInfo1 as BuyerInfo1
from openapi_client.models.by import By as By
from openapi_client.models.campaign_options import CampaignOptions as CampaignOptions
from openapi_client.models.campaign_options1 import CampaignOptions1 as CampaignOptions1
from openapi_client.models.campaign_options2 import CampaignOptions2 as CampaignOptions2
from openapi_client.models.cancel_event_request import CancelEventRequest as CancelEventRequest
from openapi_client.models.cancellation_reason import CancellationReason as CancellationReason
from openapi_client.models.cancelled_status_info import CancelledStatusInfo as CancelledStatusInfo
from openapi_client.models.case import Case as Case
from openapi_client.models.condition_action import ConditionAction as ConditionAction
from openapi_client.models.condition_action_info import ConditionActionInfo as ConditionActionInfo
from openapi_client.models.condition_block import ConditionBlock as ConditionBlock
from openapi_client.models.condition_expression_group import ConditionExpressionGroup as ConditionExpressionGroup
from openapi_client.models.condition_filter import ConditionFilter as ConditionFilter
from openapi_client.models.consume_report_event_request import ConsumeReportEventRequest as ConsumeReportEventRequest
from openapi_client.models.contact_details import ContactDetails as ContactDetails
from openapi_client.models.contact_details1 import ContactDetails1 as ContactDetails1
from openapi_client.models.count_gift_cards_request import CountGiftCardsRequest as CountGiftCardsRequest
from openapi_client.models.count_gift_cards_response import CountGiftCardsResponse as CountGiftCardsResponse
from openapi_client.models.count_gift_cards_response1 import CountGiftCardsResponse1 as CountGiftCardsResponse1
from openapi_client.models.count_wallets_request import CountWalletsRequest as CountWalletsRequest
from openapi_client.models.count_wallets_response import CountWalletsResponse as CountWalletsResponse
from openapi_client.models.count_wallets_response1 import CountWalletsResponse1 as CountWalletsResponse1
from openapi_client.models.create_access_token_response import CreateAccessTokenResponse as CreateAccessTokenResponse
from openapi_client.models.create_customer_reference_request import CreateCustomerReferenceRequest as CreateCustomerReferenceRequest
from openapi_client.models.create_customer_reference_response import CreateCustomerReferenceResponse as CreateCustomerReferenceResponse
from openapi_client.models.create_gift_card428_response import CreateGiftCard428Response as CreateGiftCard428Response
from openapi_client.models.create_gift_card_request import CreateGiftCardRequest as CreateGiftCardRequest
from openapi_client.models.create_gift_card_response import CreateGiftCardResponse as CreateGiftCardResponse
from openapi_client.models.create_gift_card_response1 import CreateGiftCardResponse1 as CreateGiftCardResponse1
from openapi_client.models.create_migration_gift_card_request import CreateMigrationGiftCardRequest as CreateMigrationGiftCardRequest
from openapi_client.models.create_migration_gift_card_response import CreateMigrationGiftCardResponse as CreateMigrationGiftCardResponse
from openapi_client.models.create_migration_recipient_request import CreateMigrationRecipientRequest as CreateMigrationRecipientRequest
from openapi_client.models.create_migration_recipient_response import CreateMigrationRecipientResponse as CreateMigrationRecipientResponse
from openapi_client.models.create_migration_transaction_request import CreateMigrationTransactionRequest as CreateMigrationTransactionRequest
from openapi_client.models.create_migration_transaction_response import CreateMigrationTransactionResponse as CreateMigrationTransactionResponse
from openapi_client.models.create_migration_wallet_action_request import CreateMigrationWalletActionRequest as CreateMigrationWalletActionRequest
from openapi_client.models.create_migration_wallet_action_response import CreateMigrationWalletActionResponse as CreateMigrationWalletActionResponse
from openapi_client.models.create_order_request import CreateOrderRequest as CreateOrderRequest
from openapi_client.models.create_order_response import CreateOrderResponse as CreateOrderResponse
from openapi_client.models.create_order_response1 import CreateOrderResponse1 as CreateOrderResponse1
from openapi_client.models.create_recipient_request import CreateRecipientRequest as CreateRecipientRequest
from openapi_client.models.create_recipient_response import CreateRecipientResponse as CreateRecipientResponse
from openapi_client.models.create_recipient_response1 import CreateRecipientResponse1 as CreateRecipientResponse1
from openapi_client.models.create_wallet_action400_response import CreateWalletAction400Response as CreateWalletAction400Response
from openapi_client.models.create_wallet_action_by_customer_reference_request import CreateWalletActionByCustomerReferenceRequest as CreateWalletActionByCustomerReferenceRequest
from openapi_client.models.create_wallet_action_by_customer_reference_response import CreateWalletActionByCustomerReferenceResponse as CreateWalletActionByCustomerReferenceResponse
from openapi_client.models.create_wallet_action_by_customer_reference_response1 import CreateWalletActionByCustomerReferenceResponse1 as CreateWalletActionByCustomerReferenceResponse1
from openapi_client.models.create_wallet_action_request import CreateWalletActionRequest as CreateWalletActionRequest
from openapi_client.models.create_wallet_action_response import CreateWalletActionResponse as CreateWalletActionResponse
from openapi_client.models.create_wallet_action_response1 import CreateWalletActionResponse1 as CreateWalletActionResponse1
from openapi_client.models.create_wallet_request import CreateWalletRequest as CreateWalletRequest
from openapi_client.models.create_wallet_response import CreateWalletResponse as CreateWalletResponse
from openapi_client.models.create_wallet_response1 import CreateWalletResponse1 as CreateWalletResponse1
from openapi_client.models.create_wallet_v2_request import CreateWalletV2Request as CreateWalletV2Request
from openapi_client.models.create_wallet_v2_response import CreateWalletV2Response as CreateWalletV2Response
from openapi_client.models.cursor_paging import CursorPaging as CursorPaging
from openapi_client.models.cursor_paging1 import CursorPaging1 as CursorPaging1
from openapi_client.models.cursor_paging2 import CursorPaging2 as CursorPaging2
from openapi_client.models.cursor_paging3 import CursorPaging3 as CursorPaging3
from openapi_client.models.cursor_paging4 import CursorPaging4 as CursorPaging4
from openapi_client.models.cursor_paging_metadata import CursorPagingMetadata as CursorPagingMetadata
from openapi_client.models.cursor_paging_metadata1 import CursorPagingMetadata1 as CursorPagingMetadata1
from openapi_client.models.cursor_paging_metadata2 import CursorPagingMetadata2 as CursorPagingMetadata2
from openapi_client.models.cursor_paging_metadata3 import CursorPagingMetadata3 as CursorPagingMetadata3
from openapi_client.models.cursors import Cursors as Cursors
from openapi_client.models.cursors1 import Cursors1 as Cursors1
from openapi_client.models.cursors2 import Cursors2 as Cursors2
from openapi_client.models.cursors3 import Cursors3 as Cursors3
from openapi_client.models.cursors4 import Cursors4 as Cursors4
from openapi_client.models.cursors5 import Cursors5 as Cursors5
from openapi_client.models.customer_reference import CustomerReference as CustomerReference
from openapi_client.models.customer_reference1 import CustomerReference1 as CustomerReference1
from openapi_client.models.customer_reference2 import CustomerReference2 as CustomerReference2
from openapi_client.models.customer_reference3 import CustomerReference3 as CustomerReference3
from openapi_client.models.customer_reference4 import CustomerReference4 as CustomerReference4
from openapi_client.models.customer_reference5 import CustomerReference5 as CustomerReference5
from openapi_client.models.customer_reference_query import CustomerReferenceQuery as CustomerReferenceQuery
from openapi_client.models.disabledatdateset import DISABLEDATDATESET as DISABLEDATDATESET
from openapi_client.models.disabledatdateset_details import DISABLEDATDATESETDetails as DISABLEDATDATESETDetails
from openapi_client.models.disabledatdateset_details_application_error import DISABLEDATDATESETDetailsApplicationError as DISABLEDATDATESETDetailsApplicationError
from openapi_client.models.date_histogram_aggregation import DateHistogramAggregation as DateHistogramAggregation
from openapi_client.models.date_histogram_result import DateHistogramResult as DateHistogramResult
from openapi_client.models.date_histogram_result1 import DateHistogramResult1 as DateHistogramResult1
from openapi_client.models.date_histogram_results import DateHistogramResults as DateHistogramResults
from openapi_client.models.date_histogram_results1 import DateHistogramResults1 as DateHistogramResults1
from openapi_client.models.decrease_balance428_response import DecreaseBalance428Response as DecreaseBalance428Response
from openapi_client.models.decrease_balance_request import DecreaseBalanceRequest as DecreaseBalanceRequest
from openapi_client.models.decrease_balance_response import DecreaseBalanceResponse as DecreaseBalanceResponse
from openapi_client.models.decrease_balance_response1 import DecreaseBalanceResponse1 as DecreaseBalanceResponse1
from openapi_client.models.delay_action import DelayAction as DelayAction
from openapi_client.models.delay_action_info import DelayActionInfo as DelayActionInfo
from openapi_client.models.delay_helper import DelayHelper as DelayHelper
from openapi_client.models.delete_customer_reference_request import DeleteCustomerReferenceRequest as DeleteCustomerReferenceRequest
from openapi_client.models.delete_order_request import DeleteOrderRequest as DeleteOrderRequest
from openapi_client.models.delete_recipient_request import DeleteRecipientRequest as DeleteRecipientRequest
from openapi_client.models.delete_wallet_action_request import DeleteWalletActionRequest as DeleteWalletActionRequest
from openapi_client.models.disable_gift_card_request import DisableGiftCardRequest as DisableGiftCardRequest
from openapi_client.models.disable_gift_card_response import DisableGiftCardResponse as DisableGiftCardResponse
from openapi_client.models.disable_gift_card_response1 import DisableGiftCardResponse1 as DisableGiftCardResponse1
from openapi_client.models.disable_wallet_action428_response import DisableWalletAction428Response as DisableWalletAction428Response
from openapi_client.models.disable_wallet_action_request import DisableWalletActionRequest as DisableWalletActionRequest
from openapi_client.models.disable_wallet_action_response import DisableWalletActionResponse as DisableWalletActionResponse
from openapi_client.models.disable_wallet_action_response1 import DisableWalletActionResponse1 as DisableWalletActionResponse1
from openapi_client.models.domain import Domain as Domain
from openapi_client.models.double_value import DoubleValue as DoubleValue
from openapi_client.models.draft_info import DraftInfo as DraftInfo
from openapi_client.models.existingidempotencykey import EXISTINGIDEMPOTENCYKEY as EXISTINGIDEMPOTENCYKEY
from openapi_client.models.existingidempotencykey_details import EXISTINGIDEMPOTENCYKEYDetails as EXISTINGIDEMPOTENCYKEYDetails
from openapi_client.models.existingidempotencykey_details_application_error import EXISTINGIDEMPOTENCYKEYDetailsApplicationError as EXISTINGIDEMPOTENCYKEYDetailsApplicationError
from openapi_client.models.expirationdateinthepast import EXPIRATIONDATEINTHEPAST as EXPIRATIONDATEINTHEPAST
from openapi_client.models.expirationdateinthepast_details import EXPIRATIONDATEINTHEPASTDetails as EXPIRATIONDATEINTHEPASTDetails
from openapi_client.models.expirationdateinthepast_details_application_error import EXPIRATIONDATEINTHEPASTDetailsApplicationError as EXPIRATIONDATEINTHEPASTDetailsApplicationError
from openapi_client.models.email_params import EmailParams as EmailParams
from openapi_client.models.email_params1 import EmailParams1 as EmailParams1
from openapi_client.models.end_migration_wallet_action_request import EndMigrationWalletActionRequest as EndMigrationWalletActionRequest
from openapi_client.models.end_migration_wallet_action_response import EndMigrationWalletActionResponse as EndMigrationWalletActionResponse
from openapi_client.models.enrichment import Enrichment as Enrichment
from openapi_client.models.enrichments import Enrichments as Enrichments
from openapi_client.models.entity_created_event import EntityCreatedEvent as EntityCreatedEvent
from openapi_client.models.entity_deleted_event import EntityDeletedEvent as EntityDeletedEvent
from openapi_client.models.entity_updated_event import EntityUpdatedEvent as EntityUpdatedEvent
from openapi_client.models.error_reason import ErrorReason as ErrorReason
from openapi_client.models.event_info import EventInfo as EventInfo
from openapi_client.models.execute_from_action_request import ExecuteFromActionRequest as ExecuteFromActionRequest
from openapi_client.models.expiration1 import Expiration1 as Expiration1
from openapi_client.models.expiration_type import ExpirationType as ExpirationType
from openapi_client.models.expression_evaluation_result import ExpressionEvaluationResult as ExpressionEvaluationResult
from openapi_client.models.expression_results import ExpressionResults as ExpressionResults
from openapi_client.models.extended_fields import ExtendedFields as ExtendedFields
from openapi_client.models.external_event import ExternalEvent as ExternalEvent
from openapi_client.models.external_event1 import ExternalEvent1 as ExternalEvent1
from openapi_client.models.external_event2 import ExternalEvent2 as ExternalEvent2
from openapi_client.models.external_event_type import ExternalEventType as ExternalEventType
from openapi_client.models.failed_status_info import FailedStatusInfo as FailedStatusInfo
from openapi_client.models.failure_info import FailureInfo as FailureInfo
from openapi_client.models.field_mask import FieldMask as FieldMask
from openapi_client.models.fields import Fields as Fields
from openapi_client.models.fields1 import Fields1 as Fields1
from openapi_client.models.fields2 import Fields2 as Fields2
from openapi_client.models.filter import Filter as Filter
from openapi_client.models.filter1 import Filter1 as Filter1
from openapi_client.models.filter2 import Filter2 as Filter2
from openapi_client.models.filter3 import Filter3 as Filter3
from openapi_client.models.filter4 import Filter4 as Filter4
from openapi_client.models.filter_value_selection import FilterValueSelection as FilterValueSelection
from openapi_client.models.filterable_app_defined_actions import FilterableAppDefinedActions as FilterableAppDefinedActions
from openapi_client.models.fixed_date import FixedDate as FixedDate
from openapi_client.models.fraud_type import FraudType as FraudType
from openapi_client.models.fulfill_order_request import FulfillOrderRequest as FulfillOrderRequest
from openapi_client.models.fulfilled_data import FulfilledData as FulfilledData
from openapi_client.models.fulfilled_data1 import FulfilledData1 as FulfilledData1
from openapi_client.models.fulfillment_status import FulfillmentStatus as FulfillmentStatus
from openapi_client.models.future_date_activation_offset import FutureDateActivationOffset as FutureDateActivationOffset
from openapi_client.models.giftcarddisabled import GIFTCARDDISABLED as GIFTCARDDISABLED
from openapi_client.models.giftcarddisabled_details import GIFTCARDDISABLEDDetails as GIFTCARDDISABLEDDetails
from openapi_client.models.giftcarddisabled_details_application_error import GIFTCARDDISABLEDDetailsApplicationError as GIFTCARDDISABLEDDetailsApplicationError
from openapi_client.models.giftcardexpired import GIFTCARDEXPIRED as GIFTCARDEXPIRED
from openapi_client.models.giftcardexpired_details import GIFTCARDEXPIREDDetails as GIFTCARDEXPIREDDetails
from openapi_client.models.giftcardexpired_details_application_error import GIFTCARDEXPIREDDetailsApplicationError as GIFTCARDEXPIREDDetailsApplicationError
from openapi_client.models.giftcardnotfound import GIFTCARDNOTFOUND as GIFTCARDNOTFOUND
from openapi_client.models.giftcardnotfound_details import GIFTCARDNOTFOUNDDetails as GIFTCARDNOTFOUNDDetails
from openapi_client.models.giftcardnotfound_details_application_error import GIFTCARDNOTFOUNDDetailsApplicationError as GIFTCARDNOTFOUNDDetailsApplicationError
from openapi_client.models.get_customer_reference_request import GetCustomerReferenceRequest as GetCustomerReferenceRequest
from openapi_client.models.get_customer_reference_response import GetCustomerReferenceResponse as GetCustomerReferenceResponse
from openapi_client.models.get_customer_reference_response1 import GetCustomerReferenceResponse1 as GetCustomerReferenceResponse1
from openapi_client.models.get_gift_card428_response import GetGiftCard428Response as GetGiftCard428Response
from openapi_client.models.get_gift_card_consistent_request import GetGiftCardConsistentRequest as GetGiftCardConsistentRequest
from openapi_client.models.get_gift_card_consistent_response import GetGiftCardConsistentResponse as GetGiftCardConsistentResponse
from openapi_client.models.get_gift_card_request import GetGiftCardRequest as GetGiftCardRequest
from openapi_client.models.get_gift_card_response import GetGiftCardResponse as GetGiftCardResponse
from openapi_client.models.get_gift_card_response1 import GetGiftCardResponse1 as GetGiftCardResponse1
from openapi_client.models.get_or_create_wallet_request import GetOrCreateWalletRequest as GetOrCreateWalletRequest
from openapi_client.models.get_or_create_wallet_response import GetOrCreateWalletResponse as GetOrCreateWalletResponse
from openapi_client.models.get_or_create_wallet_response1 import GetOrCreateWalletResponse1 as GetOrCreateWalletResponse1
from openapi_client.models.get_or_create_wallet_v2_request import GetOrCreateWalletV2Request as GetOrCreateWalletV2Request
from openapi_client.models.get_or_create_wallet_v2_response import GetOrCreateWalletV2Response as GetOrCreateWalletV2Response
from openapi_client.models.get_order_request import GetOrderRequest as GetOrderRequest
from openapi_client.models.get_order_response import GetOrderResponse as GetOrderResponse
from openapi_client.models.get_recipient_request import GetRecipientRequest as GetRecipientRequest
from openapi_client.models.get_recipient_response import GetRecipientResponse as GetRecipientResponse
from openapi_client.models.get_recipient_response1 import GetRecipientResponse1 as GetRecipientResponse1
from openapi_client.models.get_refundable_amounts_request import GetRefundableAmountsRequest as GetRefundableAmountsRequest
from openapi_client.models.get_refundable_amounts_response import GetRefundableAmountsResponse as GetRefundableAmountsResponse
from openapi_client.models.get_refundable_amounts_response1 import GetRefundableAmountsResponse1 as GetRefundableAmountsResponse1
from openapi_client.models.get_wallet_action_request import GetWalletActionRequest as GetWalletActionRequest
from openapi_client.models.get_wallet_action_response import GetWalletActionResponse as GetWalletActionResponse
from openapi_client.models.get_wallet_gift_card_request import GetWalletGiftCardRequest as GetWalletGiftCardRequest
from openapi_client.models.get_wallet_gift_card_response import GetWalletGiftCardResponse as GetWalletGiftCardResponse
from openapi_client.models.get_wallet_request import GetWalletRequest as GetWalletRequest
from openapi_client.models.get_wallet_response import GetWalletResponse as GetWalletResponse
from openapi_client.models.get_wallet_response1 import GetWalletResponse1 as GetWalletResponse1
from openapi_client.models.get_wallet_v2_request import GetWalletV2Request as GetWalletV2Request
from openapi_client.models.get_wallet_v2_response import GetWalletV2Response as GetWalletV2Response
from openapi_client.models.gift_card import GiftCard as GiftCard
from openapi_client.models.gift_card1 import GiftCard1 as GiftCard1
from openapi_client.models.gift_card2 import GiftCard2 as GiftCard2
from openapi_client.models.gift_card3 import GiftCard3 as GiftCard3
from openapi_client.models.gift_card4 import GiftCard4 as GiftCard4
from openapi_client.models.gift_card5 import GiftCard5 as GiftCard5
from openapi_client.models.gift_card6 import GiftCard6 as GiftCard6
from openapi_client.models.gift_card7 import GiftCard7 as GiftCard7
from openapi_client.models.gift_card_code_regenerated import GiftCardCodeRegenerated as GiftCardCodeRegenerated
from openapi_client.models.gift_card_disabled import GiftCardDisabled as GiftCardDisabled
from openapi_client.models.gift_card_disabled_details import GiftCardDisabledDetails as GiftCardDisabledDetails
from openapi_client.models.gift_card_expired import GiftCardExpired as GiftCardExpired
from openapi_client.models.gift_card_expired_details import GiftCardExpiredDetails as GiftCardExpiredDetails
from openapi_client.models.gift_card_gift_card_service_v1_rise_gift_cards_count_post_count_gift_cards_request_body import GiftCardGiftCardServiceV1RiseGiftCardsCountPostCountGiftCardsRequestBody as GiftCardGiftCardServiceV1RiseGiftCardsCountPostCountGiftCardsRequestBody
from openapi_client.models.gift_card_gift_card_service_v1_rise_gift_cards_gift_card_id_patch_update_gift_card_request_body import GiftCardGiftCardServiceV1RiseGiftCardsGiftCardIdPatchUpdateGiftCardRequestBody as GiftCardGiftCardServiceV1RiseGiftCardsGiftCardIdPatchUpdateGiftCardRequestBody
from openapi_client.models.gift_card_gift_card_service_v1_rise_gift_cards_post_create_gift_card_request_body import GiftCardGiftCardServiceV1RiseGiftCardsPostCreateGiftCardRequestBody as GiftCardGiftCardServiceV1RiseGiftCardsPostCreateGiftCardRequestBody
from openapi_client.models.gift_card_gift_card_service_v1_rise_gift_cards_query_post_query_gift_cards_request_body import GiftCardGiftCardServiceV1RiseGiftCardsQueryPostQueryGiftCardsRequestBody as GiftCardGiftCardServiceV1RiseGiftCardsQueryPostQueryGiftCardsRequestBody
from openapi_client.models.gift_card_gift_card_service_v1_rise_gift_cards_search_post_search_gift_cards_request_body import GiftCardGiftCardServiceV1RiseGiftCardsSearchPostSearchGiftCardsRequestBody as GiftCardGiftCardServiceV1RiseGiftCardsSearchPostSearchGiftCardsRequestBody
from openapi_client.models.gift_card_gift_card_service_v1_rise_gift_cards_transaction_gift_card_id_decrease_post_decrease_balance_request_body import GiftCardGiftCardServiceV1RiseGiftCardsTransactionGiftCardIdDecreasePostDecreaseBalanceRequestBody as GiftCardGiftCardServiceV1RiseGiftCardsTransactionGiftCardIdDecreasePostDecreaseBalanceRequestBody
from openapi_client.models.gift_card_gift_card_service_v1_rise_gift_cards_transaction_gift_card_id_increase_post_increase_balance_request_body import GiftCardGiftCardServiceV1RiseGiftCardsTransactionGiftCardIdIncreasePostIncreaseBalanceRequestBody as GiftCardGiftCardServiceV1RiseGiftCardsTransactionGiftCardIdIncreasePostIncreaseBalanceRequestBody
from openapi_client.models.gift_card_idempotency_key_details import GiftCardIdempotencyKeyDetails as GiftCardIdempotencyKeyDetails
from openapi_client.models.gift_card_info import GiftCardInfo as GiftCardInfo
from openapi_client.models.gift_card_info1 import GiftCardInfo1 as GiftCardInfo1
from openapi_client.models.gift_card_initialized import GiftCardInitialized as GiftCardInitialized
from openapi_client.models.gift_card_line_item import GiftCardLineItem as GiftCardLineItem
from openapi_client.models.gift_card_line_item1 import GiftCardLineItem1 as GiftCardLineItem1
from openapi_client.models.gift_card_not_found_details import GiftCardNotFoundDetails as GiftCardNotFoundDetails
from openapi_client.models.gift_card_options import GiftCardOptions as GiftCardOptions
from openapi_client.models.gift_card_order import GiftCardOrder as GiftCardOrder
from openapi_client.models.gift_card_order1 import GiftCardOrder1 as GiftCardOrder1
from openapi_client.models.gift_card_order2 import GiftCardOrder2 as GiftCardOrder2
from openapi_client.models.gift_card_order3 import GiftCardOrder3 as GiftCardOrder3
from openapi_client.models.gift_card_order4 import GiftCardOrder4 as GiftCardOrder4
from openapi_client.models.gift_card_order5 import GiftCardOrder5 as GiftCardOrder5
from openapi_client.models.gift_card_order_gift_card_order_service_v1_rise_orders_fulfill_post_fulfill_order_request_body import GiftCardOrderGiftCardOrderServiceV1RiseOrdersFulfillPostFulfillOrderRequestBody as GiftCardOrderGiftCardOrderServiceV1RiseOrdersFulfillPostFulfillOrderRequestBody
from openapi_client.models.gift_card_order_gift_card_order_service_v1_rise_orders_order_id_patch_update_order_request_body import GiftCardOrderGiftCardOrderServiceV1RiseOrdersOrderIdPatchUpdateOrderRequestBody as GiftCardOrderGiftCardOrderServiceV1RiseOrdersOrderIdPatchUpdateOrderRequestBody
from openapi_client.models.gift_card_order_gift_card_order_service_v1_rise_orders_post_create_order_request_body import GiftCardOrderGiftCardOrderServiceV1RiseOrdersPostCreateOrderRequestBody as GiftCardOrderGiftCardOrderServiceV1RiseOrdersPostCreateOrderRequestBody
from openapi_client.models.gift_card_order_gift_card_order_service_v1_rise_orders_query_post_query_orders_request_body import GiftCardOrderGiftCardOrderServiceV1RiseOrdersQueryPostQueryOrdersRequestBody as GiftCardOrderGiftCardOrderServiceV1RiseOrdersQueryPostQueryOrdersRequestBody
from openapi_client.models.gift_card_order_gift_card_order_service_v1_rise_orders_status_post_update_order_status_request_body import GiftCardOrderGiftCardOrderServiceV1RiseOrdersStatusPostUpdateOrderStatusRequestBody as GiftCardOrderGiftCardOrderServiceV1RiseOrdersStatusPostUpdateOrderStatusRequestBody
from openapi_client.models.gift_card_source_info1 import GiftCardSourceInfo1 as GiftCardSourceInfo1
from openapi_client.models.gift_card_source_info2 import GiftCardSourceInfo2 as GiftCardSourceInfo2
from openapi_client.models.gift_card_transaction_insufficient_funds import GiftCardTransactionInsufficientFunds as GiftCardTransactionInsufficientFunds
from openapi_client.models.gift_card_type import GiftCardType as GiftCardType
from openapi_client.models.gifting_details import GiftingDetails as GiftingDetails
from openapi_client.models.gifting_details1 import GiftingDetails1 as GiftingDetails1
from openapi_client.models.gifting_info import GiftingInfo as GiftingInfo
from openapi_client.models.gifting_info1 import GiftingInfo1 as GiftingInfo1
from openapi_client.models.group_by_value_results import GroupByValueResults as GroupByValueResults
from openapi_client.models.group_by_value_results1 import GroupByValueResults1 as GroupByValueResults1
from openapi_client.models.grouped_by_value import GroupedByValue as GroupedByValue
from openapi_client.models.helper import Helper as Helper
from openapi_client.models.insufficientfunds import INSUFFICIENTFUNDS as INSUFFICIENTFUNDS
from openapi_client.models.insufficientfunds_details import INSUFFICIENTFUNDSDetails as INSUFFICIENTFUNDSDetails
from openapi_client.models.insufficientfunds_details_application_error import INSUFFICIENTFUNDSDetailsApplicationError as INSUFFICIENTFUNDSDetailsApplicationError
from openapi_client.models.invalidcode import INVALIDCODE as INVALIDCODE
from openapi_client.models.invalidcode_details import INVALIDCODEDetails as INVALIDCODEDetails
from openapi_client.models.invalidcode_details_application_error import INVALIDCODEDetailsApplicationError as INVALIDCODEDetailsApplicationError
from openapi_client.models.invalidexpirationdate import INVALIDEXPIRATIONDATE as INVALIDEXPIRATIONDATE
from openapi_client.models.invalidexpirationdate_details import INVALIDEXPIRATIONDATEDetails as INVALIDEXPIRATIONDATEDetails
from openapi_client.models.invalidexpirationdate_details_application_error import INVALIDEXPIRATIONDATEDetailsApplicationError as INVALIDEXPIRATIONDATEDetailsApplicationError
from openapi_client.models.invalidgiftcardbalance import INVALIDGIFTCARDBALANCE as INVALIDGIFTCARDBALANCE
from openapi_client.models.invalidgiftcardbalance_details import INVALIDGIFTCARDBALANCEDetails as INVALIDGIFTCARDBALANCEDetails
from openapi_client.models.invalidgiftcardbalance_details_application_error import INVALIDGIFTCARDBALANCEDetailsApplicationError as INVALIDGIFTCARDBALANCEDetailsApplicationError
from openapi_client.models.id import Id as Id
from openapi_client.models.id1 import Id1 as Id1
from openapi_client.models.idempotency import Idempotency as Idempotency
from openapi_client.models.idempotency1 import Idempotency1 as Idempotency1
from openapi_client.models.idempotency_key_details import IdempotencyKeyDetails as IdempotencyKeyDetails
from openapi_client.models.identifier import Identifier as Identifier
from openapi_client.models.identifier_type import IdentifierType as IdentifierType
from openapi_client.models.identity import Identity as Identity
from openapi_client.models.if_filter import IfFilter as IfFilter
from openapi_client.models.include_missing_values_options import IncludeMissingValuesOptions as IncludeMissingValuesOptions
from openapi_client.models.include_missing_values_options1 import IncludeMissingValuesOptions1 as IncludeMissingValuesOptions1
from openapi_client.models.increase_balance428_response import IncreaseBalance428Response as IncreaseBalance428Response
from openapi_client.models.increase_balance_request import IncreaseBalanceRequest as IncreaseBalanceRequest
from openapi_client.models.increase_balance_response import IncreaseBalanceResponse as IncreaseBalanceResponse
from openapi_client.models.increase_balance_response1 import IncreaseBalanceResponse1 as IncreaseBalanceResponse1
from openapi_client.models.info import Info as Info
from openapi_client.models.initial_options import InitialOptions as InitialOptions
from openapi_client.models.initial_options1 import InitialOptions1 as InitialOptions1
from openapi_client.models.initiated_status_info import InitiatedStatusInfo as InitiatedStatusInfo
from openapi_client.models.initiator_type import InitiatorType as InitiatorType
from openapi_client.models.insufficient_funds_details import InsufficientFundsDetails as InsufficientFundsDetails
from openapi_client.models.int32_value import Int32Value as Int32Value
from openapi_client.models.int64_value import Int64Value as Int64Value
from openapi_client.models.interval import Interval as Interval
from openapi_client.models.invalid_code_details import InvalidCodeDetails as InvalidCodeDetails
from openapi_client.models.invalid_expiration_date_details import InvalidExpirationDateDetails as InvalidExpirationDateDetails
from openapi_client.models.invalid_gift_card_balance_details import InvalidGiftCardBalanceDetails as InvalidGiftCardBalanceDetails
from openapi_client.models.invalid_wallet_action_details import InvalidWalletActionDetails as InvalidWalletActionDetails
from openapi_client.models.item_metadata import ItemMetadata as ItemMetadata
from openapi_client.models.kind import Kind as Kind
from openapi_client.models.kind1 import Kind1 as Kind1
from openapi_client.models.list_value import ListValue as ListValue
from openapi_client.models.manual_options import ManualOptions as ManualOptions
from openapi_client.models.manual_options1 import ManualOptions1 as ManualOptions1
from openapi_client.models.manual_options2 import ManualOptions2 as ManualOptions2
from openapi_client.models.message_envelope import MessageEnvelope as MessageEnvelope
from openapi_client.models.migrate_wallet_request import MigrateWalletRequest as MigrateWalletRequest
from openapi_client.models.migrate_wallet_response import MigrateWalletResponse as MigrateWalletResponse
from openapi_client.models.migration_options import MigrationOptions as MigrationOptions
from openapi_client.models.migration_options1 import MigrationOptions1 as MigrationOptions1
from openapi_client.models.migration_options2 import MigrationOptions2 as MigrationOptions2
from openapi_client.models.missing_values import MissingValues as MissingValues
from openapi_client.models.mode import Mode as Mode
from openapi_client.models.namespaces import Namespaces as Namespaces
from openapi_client.models.nested import Nested as Nested
from openapi_client.models.nested_aggregation import NestedAggregation as NestedAggregation
from openapi_client.models.nested_aggregation_results1 import NestedAggregationResults1 as NestedAggregationResults1
from openapi_client.models.nested_aggregation_type import NestedAggregationType as NestedAggregationType
from openapi_client.models.nested_result_value1 import NestedResultValue1 as NestedResultValue1
from openapi_client.models.nested_results import NestedResults as NestedResults
from openapi_client.models.nested_results1 import NestedResults1 as NestedResults1
from openapi_client.models.nested_value_aggregation_result import NestedValueAggregationResult as NestedValueAggregationResult
from openapi_client.models.nested_value_aggregation_result1 import NestedValueAggregationResult1 as NestedValueAggregationResult1
from openapi_client.models.notifications import Notifications as Notifications
from openapi_client.models.notifications1 import Notifications1 as Notifications1
from openapi_client.models.null_value import NullValue as NullValue
from openapi_client.models.number_value import NumberValue as NumberValue
from openapi_client.models.o_auth_oauth2_token_post_some_operation_request_body import OAuthOauth2TokenPostSomeOperationRequestBody as OAuthOauth2TokenPostSomeOperationRequestBody
from openapi_client.models.of import Of as Of
from openapi_client.models.operation_type import OperationType as OperationType
from openapi_client.models.operator import Operator as Operator
from openapi_client.models.options import Options as Options
from openapi_client.models.options1 import Options1 as Options1
from openapi_client.models.order_options import OrderOptions as OrderOptions
from openapi_client.models.order_options1 import OrderOptions1 as OrderOptions1
from openapi_client.models.order_query1 import OrderQuery1 as OrderQuery1
from openapi_client.models.order_query2 import OrderQuery2 as OrderQuery2
from openapi_client.models.order_source_info import OrderSourceInfo as OrderSourceInfo
from openapi_client.models.order_source_info1 import OrderSourceInfo1 as OrderSourceInfo1
from openapi_client.models.order_status import OrderStatus as OrderStatus
from openapi_client.models.origin import Origin as Origin
from openapi_client.models.origin_info import OriginInfo as OriginInfo
from openapi_client.models.output import Output as Output
from openapi_client.models.output_action import OutputAction as OutputAction
from openapi_client.models.paging import Paging as Paging
from openapi_client.models.paging1 import Paging1 as Paging1
from openapi_client.models.paging2 import Paging2 as Paging2
from openapi_client.models.paging_metadata_v2 import PagingMetadataV2 as PagingMetadataV2
from openapi_client.models.paging_metadata_v21 import PagingMetadataV21 as PagingMetadataV21
from openapi_client.models.paging_metadata_v22 import PagingMetadataV22 as PagingMetadataV22
from openapi_client.models.paging_metadata_v23 import PagingMetadataV23 as PagingMetadataV23
from openapi_client.models.paging_metadata_v24 import PagingMetadataV24 as PagingMetadataV24
from openapi_client.models.paging_method import PagingMethod as PagingMethod
from openapi_client.models.paging_method1 import PagingMethod1 as PagingMethod1
from openapi_client.models.paging_method2 import PagingMethod2 as PagingMethod2
from openapi_client.models.paging_method3 import PagingMethod3 as PagingMethod3
from openapi_client.models.path import Path as Path
from openapi_client.models.payment_method_refund_options import PaymentMethodRefundOptions as PaymentMethodRefundOptions
from openapi_client.models.payment_method_refund_options1 import PaymentMethodRefundOptions1 as PaymentMethodRefundOptions1
from openapi_client.models.payment_method_refund_wallet_action_details import PaymentMethodRefundWalletActionDetails as PaymentMethodRefundWalletActionDetails
from openapi_client.models.payment_method_refund_wallet_action_details1 import PaymentMethodRefundWalletActionDetails1 as PaymentMethodRefundWalletActionDetails1
from openapi_client.models.payment_status import PaymentStatus as PaymentStatus
from openapi_client.models.preinstalled_identifier import PreinstalledIdentifier as PreinstalledIdentifier
from openapi_client.models.preinstalled_origin import PreinstalledOrigin as PreinstalledOrigin
from openapi_client.models.produce_transaction_added_event_request import ProduceTransactionAddedEventRequest as ProduceTransactionAddedEventRequest
from openapi_client.models.query_by_contact import QueryByContact as QueryByContact
from openapi_client.models.query_by_contact1 import QueryByContact1 as QueryByContact1
from openapi_client.models.query_gift_cards_request import QueryGiftCardsRequest as QueryGiftCardsRequest
from openapi_client.models.query_gift_cards_response import QueryGiftCardsResponse as QueryGiftCardsResponse
from openapi_client.models.query_gift_cards_response1 import QueryGiftCardsResponse1 as QueryGiftCardsResponse1
from openapi_client.models.query_orders_request import QueryOrdersRequest as QueryOrdersRequest
from openapi_client.models.query_orders_response import QueryOrdersResponse as QueryOrdersResponse
from openapi_client.models.query_orders_response1 import QueryOrdersResponse1 as QueryOrdersResponse1
from openapi_client.models.query_recipients_request import QueryRecipientsRequest as QueryRecipientsRequest
from openapi_client.models.query_recipients_response import QueryRecipientsResponse as QueryRecipientsResponse
from openapi_client.models.query_recipients_response1 import QueryRecipientsResponse1 as QueryRecipientsResponse1
from openapi_client.models.query_transactions_internal_request import QueryTransactionsInternalRequest as QueryTransactionsInternalRequest
from openapi_client.models.query_transactions_internal_response import QueryTransactionsInternalResponse as QueryTransactionsInternalResponse
from openapi_client.models.query_transactions_request import QueryTransactionsRequest as QueryTransactionsRequest
from openapi_client.models.query_transactions_response import QueryTransactionsResponse as QueryTransactionsResponse
from openapi_client.models.query_transactions_response1 import QueryTransactionsResponse1 as QueryTransactionsResponse1
from openapi_client.models.query_unredeemed_wallet_actions_request import QueryUnredeemedWalletActionsRequest as QueryUnredeemedWalletActionsRequest
from openapi_client.models.query_unredeemed_wallet_actions_response import QueryUnredeemedWalletActionsResponse as QueryUnredeemedWalletActionsResponse
from openapi_client.models.query_unredeemed_wallet_actions_response1 import QueryUnredeemedWalletActionsResponse1 as QueryUnredeemedWalletActionsResponse1
from openapi_client.models.query_v21 import QueryV21 as QueryV21
from openapi_client.models.query_v22 import QueryV22 as QueryV22
from openapi_client.models.query_wallet_action_balances_request import QueryWalletActionBalancesRequest as QueryWalletActionBalancesRequest
from openapi_client.models.query_wallet_action_balances_response import QueryWalletActionBalancesResponse as QueryWalletActionBalancesResponse
from openapi_client.models.query_wallet_action_balances_response1 import QueryWalletActionBalancesResponse1 as QueryWalletActionBalancesResponse1
from openapi_client.models.query_wallet_action_request import QueryWalletActionRequest as QueryWalletActionRequest
from openapi_client.models.query_wallet_action_response import QueryWalletActionResponse as QueryWalletActionResponse
from openapi_client.models.query_wallet_action_response1 import QueryWalletActionResponse1 as QueryWalletActionResponse1
from openapi_client.models.query_wallets_by_contact_request import QueryWalletsByContactRequest as QueryWalletsByContactRequest
from openapi_client.models.query_wallets_by_contact_response import QueryWalletsByContactResponse as QueryWalletsByContactResponse
from openapi_client.models.query_wallets_by_contact_response1 import QueryWalletsByContactResponse1 as QueryWalletsByContactResponse1
from openapi_client.models.query_wallets_request import QueryWalletsRequest as QueryWalletsRequest
from openapi_client.models.query_wallets_response import QueryWalletsResponse as QueryWalletsResponse
from openapi_client.models.query_wallets_response1 import QueryWalletsResponse1 as QueryWalletsResponse1
from openapi_client.models.requiredproperty import REQUIREDPROPERTY as REQUIREDPROPERTY
from openapi_client.models.requiredproperty_details import REQUIREDPROPERTYDetails as REQUIREDPROPERTYDetails
from openapi_client.models.requiredproperty_details_application_error import REQUIREDPROPERTYDetailsApplicationError as REQUIREDPROPERTYDetailsApplicationError
from openapi_client.models.range_aggregation import RangeAggregation as RangeAggregation
from openapi_client.models.range_aggregation_result import RangeAggregationResult as RangeAggregationResult
from openapi_client.models.range_aggregation_result1 import RangeAggregationResult1 as RangeAggregationResult1
from openapi_client.models.range_bucket import RangeBucket as RangeBucket
from openapi_client.models.range_result import RangeResult as RangeResult
from openapi_client.models.range_results import RangeResults as RangeResults
from openapi_client.models.range_results1 import RangeResults1 as RangeResults1
from openapi_client.models.rate_limit import RateLimit as RateLimit
from openapi_client.models.rate_limit_action import RateLimitAction as RateLimitAction
from openapi_client.models.rate_limit_action_info import RateLimitActionInfo as RateLimitActionInfo
from openapi_client.models.rate_limiting import RateLimiting as RateLimiting
from openapi_client.models.recipient import Recipient as Recipient
from openapi_client.models.recipient1 import Recipient1 as Recipient1
from openapi_client.models.recipient2 import Recipient2 as Recipient2
from openapi_client.models.recipient3 import Recipient3 as Recipient3
from openapi_client.models.recipient4 import Recipient4 as Recipient4
from openapi_client.models.recipient_gift_card_recipient_service_v1_rise_recipients_post_create_recipient_request_body import RecipientGiftCardRecipientServiceV1RiseRecipientsPostCreateRecipientRequestBody as RecipientGiftCardRecipientServiceV1RiseRecipientsPostCreateRecipientRequestBody
from openapi_client.models.recipient_gift_card_recipient_service_v1_rise_recipients_query_post_query_recipients_request_body import RecipientGiftCardRecipientServiceV1RiseRecipientsQueryPostQueryRecipientsRequestBody as RecipientGiftCardRecipientServiceV1RiseRecipientsQueryPostQueryRecipientsRequestBody
from openapi_client.models.redeem_options import RedeemOptions as RedeemOptions
from openapi_client.models.redeem_options1 import RedeemOptions1 as RedeemOptions1
from openapi_client.models.refresh_payload_request import RefreshPayloadRequest as RefreshPayloadRequest
from openapi_client.models.refresh_payload_response import RefreshPayloadResponse as RefreshPayloadResponse
from openapi_client.models.refresh_token_response import RefreshTokenResponse as RefreshTokenResponse
from openapi_client.models.refund_transaction_context import RefundTransactionContext as RefundTransactionContext
from openapi_client.models.refund_transaction_request import RefundTransactionRequest as RefundTransactionRequest
from openapi_client.models.refundable_amount import RefundableAmount as RefundableAmount
from openapi_client.models.refundable_amount1 import RefundableAmount1 as RefundableAmount1
from openapi_client.models.regenerate_code_request import RegenerateCodeRequest as RegenerateCodeRequest
from openapi_client.models.regenerate_code_response import RegenerateCodeResponse as RegenerateCodeResponse
from openapi_client.models.relative_expires_at import RelativeExpiresAt as RelativeExpiresAt
from openapi_client.models.relative_expires_at1 import RelativeExpiresAt1 as RelativeExpiresAt1
from openapi_client.models.report_domain_event_request import ReportDomainEventRequest as ReportDomainEventRequest
from openapi_client.models.report_event_request import ReportEventRequest as ReportEventRequest
from openapi_client.models.report_event_response import ReportEventResponse as ReportEventResponse
from openapi_client.models.report_event_response1 import ReportEventResponse1 as ReportEventResponse1
from openapi_client.models.requested_fields import RequestedFields as RequestedFields
from openapi_client.models.restore_info import RestoreInfo as RestoreInfo
from openapi_client.models.result import Result as Result
from openapi_client.models.results import Results as Results
from openapi_client.models.results1 import Results1 as Results1
from openapi_client.models.reward_options import RewardOptions as RewardOptions
from openapi_client.models.reward_options1 import RewardOptions1 as RewardOptions1
from openapi_client.models.run_automation_request import RunAutomationRequest as RunAutomationRequest
from openapi_client.models.run_automation_response import RunAutomationResponse as RunAutomationResponse
from openapi_client.models.schemavalidationfailed import SCHEMAVALIDATIONFAILED as SCHEMAVALIDATIONFAILED
from openapi_client.models.schemavalidationfailed_details import SCHEMAVALIDATIONFAILEDDetails as SCHEMAVALIDATIONFAILEDDetails
from openapi_client.models.schemavalidationfailed_details_application_error import SCHEMAVALIDATIONFAILEDDetailsApplicationError as SCHEMAVALIDATIONFAILEDDetailsApplicationError
from openapi_client.models.startdateinthepast import STARTDATEINTHEPAST as STARTDATEINTHEPAST
from openapi_client.models.startdateinthepast_details import STARTDATEINTHEPASTDetails as STARTDATEINTHEPASTDetails
from openapi_client.models.startdateinthepast_details_application_error import STARTDATEINTHEPASTDetailsApplicationError as STARTDATEINTHEPASTDetailsApplicationError
from openapi_client.models.startlaterthanexpiration import STARTLATERTHANEXPIRATION as STARTLATERTHANEXPIRATION
from openapi_client.models.startlaterthanexpiration_details import STARTLATERTHANEXPIRATIONDetails as STARTLATERTHANEXPIRATIONDetails
from openapi_client.models.startlaterthanexpiration_details_application_error import STARTLATERTHANEXPIRATIONDetailsApplicationError as STARTLATERTHANEXPIRATIONDetailsApplicationError
from openapi_client.models.scalar_aggregation import ScalarAggregation as ScalarAggregation
from openapi_client.models.scalar_result import ScalarResult as ScalarResult
from openapi_client.models.scalar_result1 import ScalarResult1 as ScalarResult1
from openapi_client.models.scalar_type import ScalarType as ScalarType
from openapi_client.models.schedule import Schedule as Schedule
from openapi_client.models.schedule_activation_requested import ScheduleActivationRequested as ScheduleActivationRequested
from openapi_client.models.schedule_request import ScheduleRequest as ScheduleRequest
from openapi_client.models.schedule_response import ScheduleResponse as ScheduleResponse
from openapi_client.models.schedule_status import ScheduleStatus as ScheduleStatus
from openapi_client.models.scheduled_action import ScheduledAction as ScheduledAction
from openapi_client.models.scheduled_status_info import ScheduledStatusInfo as ScheduledStatusInfo
from openapi_client.models.scheduler import Scheduler as Scheduler
from openapi_client.models.search_details import SearchDetails as SearchDetails
from openapi_client.models.search_gift_cards_request import SearchGiftCardsRequest as SearchGiftCardsRequest
from openapi_client.models.search_gift_cards_response import SearchGiftCardsResponse as SearchGiftCardsResponse
from openapi_client.models.search_gift_cards_response1 import SearchGiftCardsResponse1 as SearchGiftCardsResponse1
from openapi_client.models.service import Service as Service
from openapi_client.models.service_mapping import ServiceMapping as ServiceMapping
from openapi_client.models.set_variables import SetVariables as SetVariables
from openapi_client.models.set_variables_action import SetVariablesAction as SetVariablesAction
from openapi_client.models.set_variables_action_info import SetVariablesActionInfo as SetVariablesActionInfo
from openapi_client.models.side_effects import SideEffects as SideEffects
from openapi_client.models.side_effects1 import SideEffects1 as SideEffects1
from openapi_client.models.side_effects2 import SideEffects2 as SideEffects2
from openapi_client.models.simple_delay import SimpleDelay as SimpleDelay
from openapi_client.models.skip_reason import SkipReason as SkipReason
from openapi_client.models.skipped_status_info import SkippedStatusInfo as SkippedStatusInfo
from openapi_client.models.sort_direction import SortDirection as SortDirection
from openapi_client.models.sort_order import SortOrder as SortOrder
from openapi_client.models.sort_type import SortType as SortType
from openapi_client.models.sorting import Sorting as Sorting
from openapi_client.models.sorting1 import Sorting1 as Sorting1
from openapi_client.models.sorting2 import Sorting2 as Sorting2
from openapi_client.models.source import Source as Source
from openapi_client.models.spi_action import SpiAction as SpiAction
from openapi_client.models.split_action import SplitAction as SplitAction
from openapi_client.models.status import Status as Status
from openapi_client.models.status_info import StatusInfo as StatusInfo
from openapi_client.models.store_credit_context import StoreCreditContext as StoreCreditContext
from openapi_client.models.store_credit_context1 import StoreCreditContext1 as StoreCreditContext1
from openapi_client.models.store_credit_context2 import StoreCreditContext2 as StoreCreditContext2
from openapi_client.models.store_credit_issuer_type import StoreCreditIssuerType as StoreCreditIssuerType
from openapi_client.models.store_credit_options import StoreCreditOptions as StoreCreditOptions
from openapi_client.models.store_credit_options1 import StoreCreditOptions1 as StoreCreditOptions1
from openapi_client.models.store_credit_refund_options import StoreCreditRefundOptions as StoreCreditRefundOptions
from openapi_client.models.store_credit_refund_options1 import StoreCreditRefundOptions1 as StoreCreditRefundOptions1
from openapi_client.models.string_value import StringValue as StringValue
from openapi_client.models.struct import Struct as Struct
from openapi_client.models.struct_value import StructValue as StructValue
from openapi_client.models.subject_type import SubjectType as SubjectType
from openapi_client.models.success_info import SuccessInfo as SuccessInfo
from openapi_client.models.switch_filter import SwitchFilter as SwitchFilter
from openapi_client.models.tag_list import TagList as TagList
from openapi_client.models.tags import Tags as Tags
from openapi_client.models.tags_modified import TagsModified as TagsModified
from openapi_client.models.target import Target as Target
from openapi_client.models.time_period import TimePeriod as TimePeriod
from openapi_client.models.time_unit import TimeUnit as TimeUnit
from openapi_client.models.timestamp import Timestamp as Timestamp
from openapi_client.models.token_info_response import TokenInfoResponse as TokenInfoResponse
from openapi_client.models.transaction1 import Transaction1 as Transaction1
from openapi_client.models.transaction2 import Transaction2 as Transaction2
from openapi_client.models.transaction3 import Transaction3 as Transaction3
from openapi_client.models.transaction_added import TransactionAdded as TransactionAdded
from openapi_client.models.transaction_details import TransactionDetails as TransactionDetails
from openapi_client.models.transaction_details1 import TransactionDetails1 as TransactionDetails1
from openapi_client.models.transaction_options import TransactionOptions as TransactionOptions
from openapi_client.models.transaction_source_info import TransactionSourceInfo as TransactionSourceInfo
from openapi_client.models.transaction_source_info1 import TransactionSourceInfo1 as TransactionSourceInfo1
from openapi_client.models.transaction_transaction_query_service_v1_rise_gift_cards_transactions_query_post_query_transactions_request_body import TransactionTransactionQueryServiceV1RiseGiftCardsTransactionsQueryPostQueryTransactionsRequestBody as TransactionTransactionQueryServiceV1RiseGiftCardsTransactionsQueryPostQueryTransactionsRequestBody
from openapi_client.models.transaction_type import TransactionType as TransactionType
from openapi_client.models.transaction_wrapper import TransactionWrapper as TransactionWrapper
from openapi_client.models.transaction_wrapper1 import TransactionWrapper1 as TransactionWrapper1
from openapi_client.models.transaction_wrapper2 import TransactionWrapper2 as TransactionWrapper2
from openapi_client.models.transaction_wrapper3 import TransactionWrapper3 as TransactionWrapper3
from openapi_client.models.trigger import Trigger as Trigger
from openapi_client.models.trigger_info import TriggerInfo as TriggerInfo
from openapi_client.models.type import Type as Type
from openapi_client.models.type_info import TypeInfo as TypeInfo
from openapi_client.models.units import Units as Units
from openapi_client.models.update_customer_reference_request import UpdateCustomerReferenceRequest as UpdateCustomerReferenceRequest
from openapi_client.models.update_customer_reference_response import UpdateCustomerReferenceResponse as UpdateCustomerReferenceResponse
from openapi_client.models.update_gift_card_request import UpdateGiftCardRequest as UpdateGiftCardRequest
from openapi_client.models.update_gift_card_response import UpdateGiftCardResponse as UpdateGiftCardResponse
from openapi_client.models.update_gift_card_response1 import UpdateGiftCardResponse1 as UpdateGiftCardResponse1
from openapi_client.models.update_last_activity_for_reminders_request import UpdateLastActivityForRemindersRequest as UpdateLastActivityForRemindersRequest
from openapi_client.models.update_last_activity_for_reminders_response import UpdateLastActivityForRemindersResponse as UpdateLastActivityForRemindersResponse
from openapi_client.models.update_order_request import UpdateOrderRequest as UpdateOrderRequest
from openapi_client.models.update_order_response import UpdateOrderResponse as UpdateOrderResponse
from openapi_client.models.update_order_response1 import UpdateOrderResponse1 as UpdateOrderResponse1
from openapi_client.models.update_order_status_request import UpdateOrderStatusRequest as UpdateOrderStatusRequest
from openapi_client.models.update_pending_schedules_payload_request import UpdatePendingSchedulesPayloadRequest as UpdatePendingSchedulesPayloadRequest
from openapi_client.models.update_wallet_action400_response import UpdateWalletAction400Response as UpdateWalletAction400Response
from openapi_client.models.update_wallet_action428_response import UpdateWalletAction428Response as UpdateWalletAction428Response
from openapi_client.models.update_wallet_action_request import UpdateWalletActionRequest as UpdateWalletActionRequest
from openapi_client.models.update_wallet_action_response import UpdateWalletActionResponse as UpdateWalletActionResponse
from openapi_client.models.update_wallet_action_response1 import UpdateWalletActionResponse1 as UpdateWalletActionResponse1
from openapi_client.models.value1 import Value1 as Value1
from openapi_client.models.value_aggregation_result import ValueAggregationResult as ValueAggregationResult
from openapi_client.models.value_aggregation_result1 import ValueAggregationResult1 as ValueAggregationResult1
from openapi_client.models.value_result import ValueResult as ValueResult
from openapi_client.models.value_results import ValueResults as ValueResults
from openapi_client.models.value_results1 import ValueResults1 as ValueResults1
from openapi_client.models.void_failed_details import VoidFailedDetails as VoidFailedDetails
from openapi_client.models.void_options import VoidOptions as VoidOptions
from openapi_client.models.void_options1 import VoidOptions1 as VoidOptions1
from openapi_client.models.void_transaction_request import VoidTransactionRequest as VoidTransactionRequest
from openapi_client.models.void_transaction_response import VoidTransactionResponse as VoidTransactionResponse
from openapi_client.models.walletactionalreadyactive import WALLETACTIONALREADYACTIVE as WALLETACTIONALREADYACTIVE
from openapi_client.models.walletactionalreadyactive_details import WALLETACTIONALREADYACTIVEDetails as WALLETACTIONALREADYACTIVEDetails
from openapi_client.models.walletactionalreadyactive_details_application_error import WALLETACTIONALREADYACTIVEDetailsApplicationError as WALLETACTIONALREADYACTIVEDetailsApplicationError
from openapi_client.models.walletactionalreadyexpired import WALLETACTIONALREADYEXPIRED as WALLETACTIONALREADYEXPIRED
from openapi_client.models.walletactionalreadyexpired_details import WALLETACTIONALREADYEXPIREDDetails as WALLETACTIONALREADYEXPIREDDetails
from openapi_client.models.walletactionalreadyexpired_details_application_error import WALLETACTIONALREADYEXPIREDDetailsApplicationError as WALLETACTIONALREADYEXPIREDDetailsApplicationError
from openapi_client.models.walletactionexceedsmaximumbalance import WALLETACTIONEXCEEDSMAXIMUMBALANCE as WALLETACTIONEXCEEDSMAXIMUMBALANCE
from openapi_client.models.walletactionexceedsmaximumbalance_details import WALLETACTIONEXCEEDSMAXIMUMBALANCEDetails as WALLETACTIONEXCEEDSMAXIMUMBALANCEDetails
from openapi_client.models.walletactionexceedsmaximumbalance_details_application_error import WALLETACTIONEXCEEDSMAXIMUMBALANCEDetailsApplicationError as WALLETACTIONEXCEEDSMAXIMUMBALANCEDetailsApplicationError
from openapi_client.models.walletactionnotactive import WALLETACTIONNOTACTIVE as WALLETACTIONNOTACTIVE
from openapi_client.models.walletactionnotactive_details import WALLETACTIONNOTACTIVEDetails as WALLETACTIONNOTACTIVEDetails
from openapi_client.models.walletactionnotactive_details_application_error import WALLETACTIONNOTACTIVEDetailsApplicationError as WALLETACTIONNOTACTIVEDetailsApplicationError
from openapi_client.models.wallet import Wallet as Wallet
from openapi_client.models.wallet1 import Wallet1 as Wallet1
from openapi_client.models.wallet2 import Wallet2 as Wallet2
from openapi_client.models.wallet3 import Wallet3 as Wallet3
from openapi_client.models.wallet4 import Wallet4 as Wallet4
from openapi_client.models.wallet5 import Wallet5 as Wallet5
from openapi_client.models.wallet_action import WalletAction as WalletAction
from openapi_client.models.wallet_action1 import WalletAction1 as WalletAction1
from openapi_client.models.wallet_action2 import WalletAction2 as WalletAction2
from openapi_client.models.wallet_action3 import WalletAction3 as WalletAction3
from openapi_client.models.wallet_action4 import WalletAction4 as WalletAction4
from openapi_client.models.wallet_action5 import WalletAction5 as WalletAction5
from openapi_client.models.wallet_action6 import WalletAction6 as WalletAction6
from openapi_client.models.wallet_action7 import WalletAction7 as WalletAction7
from openapi_client.models.wallet_action8 import WalletAction8 as WalletAction8
from openapi_client.models.wallet_action_creation_disabled_at_date_set_details import WalletActionCreationDisabledAtDateSetDetails as WalletActionCreationDisabledAtDateSetDetails
from openapi_client.models.wallet_action_creation_expiration_date_in_the_past_details import WalletActionCreationExpirationDateInThePastDetails as WalletActionCreationExpirationDateInThePastDetails
from openapi_client.models.wallet_action_creation_start_later_than_expiration_details import WalletActionCreationStartLaterThanExpirationDetails as WalletActionCreationStartLaterThanExpirationDetails
from openapi_client.models.wallet_action_disabled import WalletActionDisabled as WalletActionDisabled
from openapi_client.models.wallet_action_end_options import WalletActionEndOptions as WalletActionEndOptions
from openapi_client.models.wallet_action_end_options1 import WalletActionEndOptions1 as WalletActionEndOptions1
from openapi_client.models.wallet_action_end_reason import WalletActionEndReason as WalletActionEndReason
from openapi_client.models.wallet_action_exceeds_maximum_balance_details import WalletActionExceedsMaximumBalanceDetails as WalletActionExceedsMaximumBalanceDetails
from openapi_client.models.wallet_action_execution_details import WalletActionExecutionDetails as WalletActionExecutionDetails
from openapi_client.models.wallet_action_execution_details1 import WalletActionExecutionDetails1 as WalletActionExecutionDetails1
from openapi_client.models.wallet_action_execution_details2 import WalletActionExecutionDetails2 as WalletActionExecutionDetails2
from openapi_client.models.wallet_action_expired import WalletActionExpired as WalletActionExpired
from openapi_client.models.wallet_action_idempotency_key_details import WalletActionIdempotencyKeyDetails as WalletActionIdempotencyKeyDetails
from openapi_client.models.wallet_action_start_options import WalletActionStartOptions as WalletActionStartOptions
from openapi_client.models.wallet_action_start_options1 import WalletActionStartOptions1 as WalletActionStartOptions1
from openapi_client.models.wallet_action_started import WalletActionStarted as WalletActionStarted
from openapi_client.models.wallet_action_status import WalletActionStatus as WalletActionStatus
from openapi_client.models.wallet_action_type import WalletActionType as WalletActionType
from openapi_client.models.wallet_action_update_expiration_date_in_the_past_details import WalletActionUpdateExpirationDateInThePastDetails as WalletActionUpdateExpirationDateInThePastDetails
from openapi_client.models.wallet_action_update_start_date_in_the_past_details import WalletActionUpdateStartDateInThePastDetails as WalletActionUpdateStartDateInThePastDetails
from openapi_client.models.wallet_action_update_start_later_than_expiration_details import WalletActionUpdateStartLaterThanExpirationDetails as WalletActionUpdateStartLaterThanExpirationDetails
from openapi_client.models.wallet_action_wallet_action_service_v1_rise_wallet_actions_by_customer_reference_post_create_wallet_action_by_customer_reference_request_body import WalletActionWalletActionServiceV1RiseWalletActionsByCustomerReferencePostCreateWalletActionByCustomerReferenceRequestBody as WalletActionWalletActionServiceV1RiseWalletActionsByCustomerReferencePostCreateWalletActionByCustomerReferenceRequestBody
from openapi_client.models.wallet_action_wallet_action_service_v1_rise_wallet_actions_post_create_wallet_action_request_body import WalletActionWalletActionServiceV1RiseWalletActionsPostCreateWalletActionRequestBody as WalletActionWalletActionServiceV1RiseWalletActionsPostCreateWalletActionRequestBody
from openapi_client.models.wallet_action_wallet_action_service_v1_rise_wallet_actions_query_balances_post_query_wallet_actions_balances_request_body import WalletActionWalletActionServiceV1RiseWalletActionsQueryBalancesPostQueryWalletActionsBalancesRequestBody as WalletActionWalletActionServiceV1RiseWalletActionsQueryBalancesPostQueryWalletActionsBalancesRequestBody
from openapi_client.models.wallet_action_wallet_action_service_v1_rise_wallet_actions_query_post_query_wallet_actions_request_body import WalletActionWalletActionServiceV1RiseWalletActionsQueryPostQueryWalletActionsRequestBody as WalletActionWalletActionServiceV1RiseWalletActionsQueryPostQueryWalletActionsRequestBody
from openapi_client.models.wallet_action_wallet_action_service_v1_rise_wallet_actions_query_unredeemed_post_query_unredeemed_wallet_actions_request_body import WalletActionWalletActionServiceV1RiseWalletActionsQueryUnredeemedPostQueryUnredeemedWalletActionsRequestBody as WalletActionWalletActionServiceV1RiseWalletActionsQueryUnredeemedPostQueryUnredeemedWalletActionsRequestBody
from openapi_client.models.wallet_action_wallet_action_service_v1_rise_wallet_actions_wallet_action_id_disable_post_disable_wallet_action_request_body import WalletActionWalletActionServiceV1RiseWalletActionsWalletActionIdDisablePostDisableWalletActionRequestBody as WalletActionWalletActionServiceV1RiseWalletActionsWalletActionIdDisablePostDisableWalletActionRequestBody
from openapi_client.models.wallet_action_wallet_action_service_v1_rise_wallet_actions_wallet_action_id_patch_update_wallet_action_request_body import WalletActionWalletActionServiceV1RiseWalletActionsWalletActionIdPatchUpdateWalletActionRequestBody as WalletActionWalletActionServiceV1RiseWalletActionsWalletActionIdPatchUpdateWalletActionRequestBody
from openapi_client.models.wallet_action_with_balance import WalletActionWithBalance as WalletActionWithBalance
from openapi_client.models.wallet_action_with_balance1 import WalletActionWithBalance1 as WalletActionWithBalance1
from openapi_client.models.wallet_wallet_service_v1_rise_wallets_count_post_count_wallets_request_body import WalletWalletServiceV1RiseWalletsCountPostCountWalletsRequestBody as WalletWalletServiceV1RiseWalletsCountPostCountWalletsRequestBody
from openapi_client.models.wallet_wallet_service_v1_rise_wallets_issue_post_get_or_create_wallet_request_body import WalletWalletServiceV1RiseWalletsIssuePostGetOrCreateWalletRequestBody as WalletWalletServiceV1RiseWalletsIssuePostGetOrCreateWalletRequestBody
from openapi_client.models.wallet_wallet_service_v1_rise_wallets_post_create_wallet_request_body import WalletWalletServiceV1RiseWalletsPostCreateWalletRequestBody as WalletWalletServiceV1RiseWalletsPostCreateWalletRequestBody
from openapi_client.models.wallet_wallet_service_v1_rise_wallets_query_by_contact_post_query_wallets_by_contact_request_body import WalletWalletServiceV1RiseWalletsQueryByContactPostQueryWalletsByContactRequestBody as WalletWalletServiceV1RiseWalletsQueryByContactPostQueryWalletsByContactRequestBody
from openapi_client.models.wallet_wallet_service_v1_rise_wallets_query_post_query_wallets_request_body import WalletWalletServiceV1RiseWalletsQueryPostQueryWalletsRequestBody as WalletWalletServiceV1RiseWalletsQueryPostQueryWalletsRequestBody
from openapi_client.models.webhook_identity_type import WebhookIdentityType as WebhookIdentityType
from openapi_client.models.workflow_options import WorkflowOptions as WorkflowOptions
from openapi_client.models.workflow_options1 import WorkflowOptions1 as WorkflowOptions1
from openapi_client.models.workflows_esb_config_resolver_workflows_v1_events_report_post_report_event_request_body import WorkflowsEsbConfigResolverWorkflowsV1EventsReportPostReportEventRequestBody as WorkflowsEsbConfigResolverWorkflowsV1EventsReportPostReportEventRequestBody

